import {chromium,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
const b=await chromium.launch({channel:'chrome'}),p=await b.newPage({viewport:{width:390,height:844}});
const feed=JSON.parse(await readFile('artifacts/morning-brew-v2/feed-evidence.json','utf8'));
await p.goto('http://localhost:3012/staff');await p.getByRole('button',{name:/Camila/}).click();await p.getByRole('button',{name:'Looks good',exact:true}).click();await p.getByRole('button',{name:/Make my Morning Brew/}).click();await expect(p.locator('.brew-live-news .brew-news-card').first()).toBeVisible({timeout:30000});
await p.screenshot({path:'artifacts/morning-brew-v2/chrome-phone.png',fullPage:true});console.log('PHONE OVERFLOW',await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth));
// These responses exist only in this test browser; the real server cache is untouched.
const pattern='**/v1/staff/morning-brew/news?*';
await p.route(pattern,r=>r.fulfill({json:{...feed,state:'empty',articles:[],message:null}}));await p.getByRole('button',{name:'Refresh news',exact:true}).click();await expect(p.getByText('The publisher has no dated articles available.')).toBeVisible();
await p.unroute(pattern);await p.route(pattern,r=>r.fulfill({status:503,json:{error:{code:'UNAVAILABLE',message:'Test-only unavailable'}}}));await p.getByRole('button',{name:'Refresh news',exact:true}).click();await expect(p.getByText('News could not be refreshed. Check your connection and try again.')).toBeVisible();
await p.unroute(pattern);await p.route(pattern,r=>r.fulfill({json:{...feed,state:'stale',message:'Publisher retrieval failed. Showing the last successful feed.'}}));await p.route('https://imgproxy.divecdn.com/**',r=>r.abort());await p.getByRole('button',{name:'Refresh news',exact:true}).click();await expect(p.getByText(/Publisher retrieval failed/)).toBeVisible();await expect(p.locator('.brew-news-card__fallback').first()).toBeVisible();await p.screenshot({path:'artifacts/morning-brew-v2/chrome-news-stale.png'});
await p.unroute(pattern);let release;const gate=new Promise(r=>release=r);await p.route(pattern,async r=>{await gate;await r.fulfill({json:feed});});await p.getByRole('button',{name:'Refresh news',exact:true}).click();await expect(p.getByRole('button',{name:'Refreshing…',exact:true})).toBeDisabled();release();await expect(p.getByRole('button',{name:'Refresh news',exact:true})).toBeEnabled();await p.unroute(pattern);await p.unroute('https://imgproxy.divecdn.com/**');
const email=p.locator('.brew-panel[aria-labelledby=emails-title]');await email.getByRole('tab',{name:/Waiting on replies/}).click();await expect(email.locator('.brew-panel__empty')).toBeVisible();await email.getByRole('tab',{name:/Important unread/}).click();await expect(email.locator('.brew-email-row')).toHaveCount(4);await email.getByRole('tab',{name:/Your response/}).click();await expect(email.locator('.brew-email-row')).toHaveCount(4);
await p.locator('.brew-calendar-row').first().getByRole('button').first().click();await p.getByRole('button',{name:'Unhelpful prep',exact:true}).click();await p.getByRole('checkbox',{name:'Missing context',exact:true}).check();await p.locator('textarea[name=comment]').fill('Keep this note on retry');await p.route('**/v1/staff/morning-brew/prep-feedback',r=>r.fulfill({status:503,json:{error:{code:'UNAVAILABLE',message:'Test failure'}}}));await p.getByRole('button',{name:'Submit',exact:true}).click();await expect(p.getByText(/Feedback could not be saved/)).toBeVisible();await expect(p.locator('textarea[name=comment]')).toHaveValue('Keep this note on retry');await expect(p.getByRole('checkbox',{name:'Missing context',exact:true})).toBeChecked();await p.screenshot({path:'artifacts/morning-brew-v2/chrome-feedback-error-phone.png'});await p.unroute('**/v1/staff/morning-brew/prep-feedback');await p.getByRole('button',{name:'Skip details',exact:true}).click();await expect(p.getByText('Feedback saved for this demo prep sheet. Thank you.')).toBeVisible();await p.keyboard.press('Escape');
await p.route('**/v1/staff/morning-brew/team-settings',async r=>{const response=await r.fetch();await r.fulfill({response,json:{...(await response.json()),canManage:false}});});await p.reload();await p.getByRole('button',{name:'Change what’s in it',exact:true}).click();await p.getByRole('button',{name:'Looks good',exact:true}).click();await expect(p.getByRole('switch',{name:'Remove Institutional Intelligence'})).toBeDisabled();await expect(p.getByText(/Your team administrator controls visibility/)).toBeVisible();
console.log('PASS loading, empty, failure, stale cache, broken image fallback, email category filters/empty, feedback retry preservation/skip, read-only team UI');await b.close();
