import {chromium,webkit,expect} from '@playwright/test';
import assert from 'node:assert/strict';
import {writeFile} from 'node:fs/promises';
const engine=process.env.MB_BROWSER||'chrome';
const browser=engine==='webkit'?await webkit.launch({executablePath:'/tmp/morning-brew-v2-webkit/run'}):await chromium.launch({channel:'chrome'});
const page=await browser.newPage({viewport:{width:1440,height:900}});
const errors=[],report=[];page.on('pageerror',e=>errors.push(e.message));
const pass=s=>{report.push(s);console.log('PASS',s)};
await page.goto('http://localhost:3012/staff');await page.getByRole('button',{name:/Camila/}).click();await page.getByRole('button',{name:'Looks good',exact:true}).click();await page.getByRole('button',{name:/Make my Morning Brew/}).click();
await expect(page.locator('.brew-live-news .brew-news-card').first()).toBeVisible({timeout:30000});
const cards=page.locator('.brew-live-news .brew-news-card');
assert.ok(await cards.count()>4);
const geometry=await cards.evaluateAll(es=>es.slice(0,5).map(e=>{const r=e.getBoundingClientRect();return {y:r.y,x:r.x,width:r.width}}));assert.equal(new Set(geometry.map(r=>r.y)).size,1);assert.ok(geometry[4].x>geometry[0].x+geometry[0].width*4);
await expect(page.getByRole('button',{name:'Previous news',exact:true})).toBeDisabled();
await page.getByRole('button',{name:'Next news',exact:true}).click();await expect.poll(()=>page.locator('#brew-news-rail').evaluate(e=>e.scrollLeft)).toBeGreaterThan(500);
await expect(page.getByRole('button',{name:'Previous news',exact:true})).toBeEnabled();
await page.getByRole('button',{name:'Previous news',exact:true}).click();await expect.poll(()=>page.locator('#brew-news-rail').evaluate(e=>e.scrollLeft)).toBeLessThan(3);
await page.getByRole('button',{name:'Next news',exact:true}).focus();await page.keyboard.press('Enter');await expect.poll(()=>page.locator('#brew-news-rail').evaluate(e=>e.scrollLeft)).toBeGreaterThan(500);
await page.getByRole('button',{name:'Next news',exact:true}).click();await expect(page.getByRole('button',{name:'Next news',exact:true})).toBeDisabled();
pass('News: four equal cards on one row, all articles accessible, carousel boundaries and keyboard');
assert.equal(await page.locator('.brew-colophon button').count(),1);await expect(page.locator('.brew-colophon')).not.toContainText('All times');
await page.locator('.brew-colophon button').click();await expect(page.getByRole('button',{name:'Looks good',exact:true})).toBeVisible();await page.getByRole('button',{name:'Looks good',exact:true}).click();await page.getByRole('button',{name:'Save it',exact:true}).click();pass('Footer opens the first Morning Brew onboarding step');
await page.getByRole('button',{name:/Task Board/}).first().click();await page.getByRole('button',{name:'For You 3 views'}).click();
const frame=page.frames().find(f=>f.url().includes('action-center-demo'));
await expect(frame.locator('#task-summary')).toBeVisible();
const expected=await frame.evaluate(async()=>{const {store}=await import('/action-center-demo/src/store.js');return {total:store.tasks.length,open:store.tasks.filter(t=>t.status!=='completed').length,completed:store.tasks.filter(t=>t.status==='completed').length,keys:store.tasks.map(t=>t.key),scopes:Object.fromEntries(['ML','TEAM','EG'].map(id=>[id,store.tasks.filter(t=>t.owner===id).length]))}});
assert.ok(expected.total>50);
const apiTotal=await frame.evaluate(async()=>{const {boardRequest}=await import('/action-center-demo/src/identities.js');return (await boardRequest('demo-identities')).cards.length;});assert.equal(expected.total,apiTotal);
for(const version of ['board','focus','portfolio']){
 await frame.locator(`[data-version=${version}]`).click();
 await expect(frame.locator('.sum-metric[data-bucket=open]')).toHaveAttribute('data-count',String(expected.open));
 await expect(frame.locator('.sum-metric[data-bucket=completed]')).toHaveAttribute('data-count',String(expected.completed));
 await frame.locator('.sum-status-tabs [data-bucket=all]').click();await expect(frame.locator('.sum-match-count')).toHaveText(`${expected.total} matching tasks`);
 await frame.locator('#sum-owner').selectOption('TEAM');await expect(frame.locator('.sum-match-count')).toHaveText(`${expected.scopes.TEAM} matching tasks`);
 await frame.locator('#sum-owner').selectOption('EG');await expect(frame.locator('.sum-match-count')).toHaveText(`${expected.scopes.EG} matching task${expected.scopes.EG===1?'':'s'}`);
 await frame.locator('#sum-owner').selectOption('ML');await expect(frame.locator('.sum-match-count')).toHaveText(`${expected.scopes.ML} matching tasks`);
 await frame.locator('#sum-owner').selectOption('all');
 await frame.locator('#sum-search').fill('thiswillmatchnotasks');await expect(frame.getByRole('heading',{name:'No tasks in this view'})).toBeVisible();await frame.getByRole('button',{name:'Reset filters'}).click();
}
pass('All three designs reconcile the full authorized dataset; personal/team/agent scopes and empty states');
// Search survives switching designs; scope, area and status combine predictably.
await frame.locator('[data-version=board]').click();await frame.locator('#sum-space').selectOption('fa');await frame.locator('#sum-search').fill('FIN');
const scopedText=await frame.locator('.sum-match-count').innerText();for(const v of ['focus','portfolio','board']){await frame.locator(`[data-version=${v}]`).click();await expect(frame.locator('#sum-search')).toHaveValue('FIN');await expect(frame.locator('#sum-space')).toHaveValue('fa');await expect(frame.locator('.sum-match-count')).toHaveText(scopedText);}
await frame.getByRole('button',{name:'Clear filters',exact:true}).click();await frame.locator('#sum-group').selectOption('area');await expect(frame.locator('.sum-lane')).toHaveCount(3);await frame.locator('#sum-group').selectOption('attention');
const lane=frame.locator('.sum-lane').first(),firstKey=await lane.locator('[data-summary-task]').first().getAttribute('data-summary-task');await lane.locator('[data-direction="1"]').click();assert.notEqual(await lane.locator('[data-summary-task]').first().getAttribute('data-summary-task'),firstKey);await lane.locator('[data-direction="-1"]').click();await expect(lane.locator('[data-summary-task]').first()).toHaveAttribute('data-summary-task',firstKey);
// A resize/update while typing must not replace the focused search control.
const searchHandle=await frame.locator('#sum-search').elementHandle();
await frame.locator('#sum-search').pressSequentially('FIN',{delay:35});await frame.evaluate(()=>{window.dispatchEvent(new Event('resize'));window.dispatchEvent(new Event('audentra:demo-tasks-changed'));});await frame.locator('#sum-search').pressSequentially('-2',{delay:35});await expect(frame.locator('#sum-search')).toHaveValue('FIN-2');assert.equal(await searchHandle.evaluate(e=>e.isConnected),true);await frame.locator('#sum-search').evaluate(e=>e.select());await frame.evaluate(()=>window.dispatchEvent(new Event('resize')));await page.waitForTimeout(180);await frame.locator('#sum-search').press('Backspace');await expect(frame.locator('#sum-search')).toHaveValue('');
pass('Shared filters persist between designs; area grouping, lane pagination, and stable search during resize/update work');
await frame.locator('[data-version=focus]').click();await frame.locator('[data-preview-task]').nth(1).click();const chosen=await frame.locator('[data-preview-task][aria-pressed=true]').getAttribute('data-preview-task');await expect(frame.locator('.sum-preview [data-summary-task]')).toHaveAttribute('data-summary-task',chosen);await frame.locator('.sum-preview [data-summary-task]').click();await expect(frame.locator('#task-dialog')).toHaveAttribute('open','');await page.keyboard.press('Escape');await expect(frame.locator('#task-dialog')).not.toHaveAttribute('open','');await expect.poll(()=>page.locator('#approved-task-board').evaluate(e=>e.getBoundingClientRect().left)).toBeGreaterThan(0);await expect(frame.locator('#task-summary')).toBeVisible();await expect(frame.locator('[data-version=focus]')).toHaveAttribute('aria-pressed','true');
pass('Focus selection opens the matching task and retains view when closing');
await frame.locator('[data-version=portfolio]').click();await frame.locator('.sum-stack button').first().click();await expect(frame.locator('.sum-dialog')).toHaveAttribute('open','');assert.ok(await frame.locator('.sum-dialog [data-summary-task]').count()>0);await frame.locator('.sum-dialog [data-summary-task]').first().click();await expect(frame.locator('#task-dialog')).toHaveAttribute('open','');await page.keyboard.press('Escape');await expect(frame.locator('#task-dialog')).not.toHaveAttribute('open','');await expect.poll(()=>page.locator('#approved-task-board').evaluate(e=>e.getBoundingClientRect().left)).toBeGreaterThan(0);await frame.getByRole('button',{name:'Show Team queue tasks'}).click();await expect(frame.locator('#sum-owner')).toHaveValue('TEAM');await frame.getByRole('button',{name:'Clear filters',exact:true}).click();
pass('Portfolio chart segments drill into actual tasks; ownership filters work');
// Open every task using rendered controls (no financial or messaging writes).
await frame.locator('[data-version=board]').click();await frame.locator('.sum-status-tabs [data-bucket=all]').click();
for(const key of expected.keys){await frame.locator('#sum-search').fill(key);await expect(frame.locator('.sum-match-count'),`search for ${key}`).toHaveText('1 matching task');await frame.locator('#task-summary [data-summary-task]').first().click();await expect(frame.locator('#task-dialog')).toHaveAttribute('open','');await expect(frame.locator('#task-title')).not.toBeEmpty();await page.keyboard.press('Escape');await expect(frame.locator('#task-dialog')).not.toHaveAttribute('open','');await expect.poll(()=>page.locator('#approved-task-board').evaluate(e=>e.getBoundingClientRect().left)).toBeGreaterThan(0);}
await frame.locator('#sum-search').fill('');pass(`Every one of ${expected.total} task cards opens its existing detail workspace`);
// One reversible demo workflow transition, via the actual task control; restore afterwards.
const transition=await frame.evaluate(async()=>{const {store}=await import('/action-center-demo/src/store.js');const t=store.tasks.find(t=>t.type==='outreach'&&t.status==='responded');window.__summaryRestore={task:structuredClone(t),clock:store.clock};return t?.key;});
assert.ok(transition);
try{await page.evaluate(()=>{const notice=document.createElement('section');notice.id='summary-test-notice';notice.className='staff-realtime-notice';notice.textContent='Verification: a canonical data update is available.';document.body.append(notice);});await frame.locator('#sum-search').fill(transition);await frame.locator('#task-summary [data-summary-task]').click();await frame.locator('[data-action="transition:completed"]').click();await page.keyboard.press('Escape');await expect(frame.locator('#task-dialog')).not.toHaveAttribute('open','');await expect.poll(()=>page.locator('#approved-task-board').evaluate(e=>e.getBoundingClientRect().left)).toBeGreaterThan(0);await frame.locator('#sum-search').fill('');for(const version of ['board','focus','portfolio']){await frame.locator(`[data-version=${version}]`).click();await expect(frame.locator('.sum-metric[data-bucket=open]')).toHaveAttribute('data-count',String(expected.open-1));await expect(frame.locator('.sum-metric[data-bucket=completed]')).toHaveAttribute('data-count',String(expected.completed+1));}}
finally{await page.evaluate(()=>document.querySelector('#summary-test-notice')?.remove());await frame.evaluate(async()=>{const {store,save}=await import('/action-center-demo/src/store.js');const before=window.__summaryRestore;store.tasks[store.tasks.findIndex(t=>t.key===before.task.key)]=before.task;store.clock=before.clock;save();delete window.__summaryRestore;});}
await expect(frame.locator('.sum-metric[data-bucket=open]')).toHaveAttribute('data-count',String(expected.open));pass('Actual demo Complete outreach action updates all three views; original demo state restored');
// API refresh failure must retain loaded data and recover.
await page.route('**/v1/staff/demo-task-board',route=>route.fulfill({status:503,contentType:'application/json',body:'{"detail":"Unavailable"}'}));await frame.getByRole('button',{name:'Refresh',exact:true}).click();await expect(frame.locator('.sum-error')).toBeVisible();await expect(frame.locator('.sum-source-count')).toHaveAttribute('data-total',String(expected.total));await page.unroute('**/v1/staff/demo-task-board');await frame.getByRole('button',{name:'Try again',exact:true}).click();await expect(frame.locator('.sum-error')).toHaveCount(0);pass('Refresh failure retains data; retry recovers');
if(await page.getByRole('button',{name:'Dismiss realtime update'}).isVisible())await page.getByRole('button',{name:'Dismiss realtime update'}).click();
await frame.getByRole('button',{name:'How priorities work'}).click();await expect(frame.getByRole('heading',{name:'How priorities work'})).toBeVisible();await page.keyboard.press('Escape');await expect(frame.locator('#task-dialog')).not.toHaveAttribute('open','');await expect.poll(()=>page.locator('#approved-task-board').evaluate(e=>e.getBoundingClientRect().left)).toBeGreaterThan(0);
// Returning to normal boards preserves their independent filters.
await page.locator('[data-approved-board="fa-outreach"]:visible').click();await expect(frame.locator('#task-summary')).toBeHidden();await frame.locator('#board-search').fill('FIN');await page.getByRole('button',{name:'For You 3 views'}).click();await page.locator('[data-approved-board="fa-outreach"]:visible').click();await expect(frame.locator('#board-search')).toHaveValue('FIN');await frame.locator('#board-search').fill('');await page.getByRole('button',{name:'For You 3 views'}).click();await page.locator('[data-portal-item=tasks]:visible').click();await expect(frame.locator('#task-summary')).toBeHidden();await expect(frame.locator('#board-search')).toBeVisible();await page.getByRole('button',{name:'For You 3 views'}).click();pass('Existing board filters survive summary navigation; Task Board parent returns to the original board');
await expect(frame.locator('#task-summary')).toBeVisible();await frame.locator('[data-version=board]').focus();await expect(frame.locator('[data-version=board]')).toBeFocused();await frame.locator('[data-version=board]').press('Enter');await expect(frame.locator('[data-version=board]')).toHaveAttribute('aria-pressed','true');await expect(frame.locator('[data-version=board]')).toBeFocused();await frame.locator('[data-version=board]').press('/');await expect(frame.locator('#sum-search')).toBeFocused();pass('Keyboard design switch retains focus; slash search shortcut and priority explanation accessible');
assert.deepEqual(errors,[]);await writeFile(`artifacts/morning-brew-v2/${engine}-summary-results.json`,JSON.stringify({engine,report,errors,total:expected.total},null,2));await browser.close();console.log('ALL PASS',engine);
