import { chromium, webkit, expect } from '@playwright/test';
import { writeFile } from 'node:fs/promises';
const engine=process.env.MB_BROWSER||'chrome';
const browser=engine==='webkit'?await webkit.launch({executablePath:'/tmp/morning-brew-v2-webkit/run'}):await chromium.launch({channel:'chrome'});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto((process.env.PORTAL_URL||'http://localhost:3012')+'/staff');
await page.getByRole('button',{name:/Camila/}).click();
await page.getByRole('button',{name:'Looks good',exact:true}).click();
await expect(page.getByRole('switch',{name:'Remove Institutional Intelligence'})).toBeEnabled();
await page.getByRole('button',{name:/Make my Morning Brew/}).click();
await expect(page.locator('.brew-live-news .brew-news-card').first()).toBeVisible({timeout:30000});

// Team setting is saved through the existing customization flow.
await page.getByRole('button',{name:'Change what’s in it',exact:true}).click();
await page.getByRole('button',{name:'Looks good',exact:true}).click();
await page.getByRole('switch',{name:'Remove Institutional Intelligence'}).click();
await page.getByRole('button',{name:'Save it',exact:true}).click();
await expect(page.getByRole('heading',{name:'Institutional Pulse',exact:false})).toBeVisible();
await expect(page.getByRole('heading',{name:/Institutional Intelligence/})).toHaveCount(0);
await page.reload();
await expect(page.getByRole('heading',{name:'Institutional Pulse',exact:false})).toBeVisible();
await expect(page.getByRole('heading',{name:/Institutional Intelligence/})).toHaveCount(0);
await page.getByRole('button',{name:'Change what’s in it',exact:true}).click();
await page.getByRole('button',{name:'Looks good',exact:true}).click();
await expect(page.getByRole('switch',{name:'Add Institutional Intelligence'})).toHaveAttribute('aria-checked','false');
await page.getByRole('switch',{name:'Add Institutional Intelligence'}).click();
await expect(page.locator('.brew-provisional')).toBeVisible();
await page.screenshot({path:'artifacts/morning-brew-v2/'+engine+'-final-customization.png'});
await page.getByRole('button',{name:'Save it',exact:true}).click();
await expect(page.getByRole('heading',{name:/Institutional Intelligence/})).toBeVisible();
console.log('PASS team toggle persisted through reload, restored enabled');
await page.locator('.brew-email-row').filter({hasText:'1:1 with Provost'}).getByRole('button').first().click();
const draft=page.getByRole('textbox',{name:'Draft for you',exact:true});
await draft.fill('My retained demo reply');
await page.getByRole('button',{name:/Check calendar/}).click();
await expect(draft).toHaveValue('My retained demo reply');
await page.getByRole('button',{name:'Regenerate reply with this time'}).click();
await expect(draft).toHaveValue(/My retained demo reply[\s\S]*Proposed time:/);
await expect(page.getByRole('button',{name:'Create calendar invite',exact:true})).toBeDisabled();
await page.getByRole('textbox',{name:'What to change',exact:true}).fill('Make this shorter');
await expect(page.getByRole('button',{name:'Ask Edward to revise draft'})).toHaveText('↑');
await page.getByRole('textbox',{name:'What to change',exact:true}).scrollIntoViewIfNeeded();
await page.screenshot({path:'artifacts/morning-brew-v2/'+engine+'-final-draft.png'});
await page.getByRole('button',{name:'Hide calendar context'}).click();
await page.getByRole('button',{name:'Send reply',exact:true}).click();
await expect(page.getByText('Reply recorded for this demo session. No email was sent.')).toBeVisible();
await page.keyboard.press('Escape');
console.log('PASS draft retention, proposal, separated edit arrow, disabled invite, demo-only send');
console.log('UPDATED COUNTS',await page.locator('.brew-email-counts').innerText());
await page.locator('.brew-calendar-row').first().getByRole('button').first().click();
await page.getByRole('button',{name:'Helpful prep',exact:true}).click();
await page.getByRole('checkbox',{name:'Useful context'}).check();
await page.locator('textarea[name=comment]').fill('Demo verification: useful agenda context.');
const saved=page.waitForResponse(r=>r.url().includes('/morning-brew/prep-feedback')&&r.request().method()==='POST');
await page.getByRole('button',{name:'Submit',exact:true}).click();
console.log('FEEDBACK', (await saved).status());
await expect(page.getByText('Feedback saved for this demo prep sheet. Thank you.')).toBeVisible();
await page.screenshot({path:'artifacts/morning-brew-v2/'+engine+'-final-prep.png'});
await page.keyboard.press('Escape');
await page.locator('.brew-kpi').first().getByRole('button',{name:/what would you like/}).click();
await page.locator('#staff-edward-message').fill('Explain this Pulse card and its comparison.');
const answer=page.waitForResponse(r=>r.url().includes('/staff/assistant/messages')&&r.request().method()==='POST',{timeout:60000});
await page.getByRole('button',{name:'Send message',exact:true}).click();
console.log('EDWARD RESPONSE',(await answer).status());
await expect(page.getByText(/The demo Pulse card you opened shows Applications: 14,782/)).toBeVisible({timeout:60000});
await page.screenshot({path:'artifacts/morning-brew-v2/'+engine+'-final-edward.png'});
await page.getByRole('button',{name:'Close Edward',exact:true}).click();
await page.locator('.brew-live-news').scrollIntoViewIfNeeded();
await page.getByRole('button',{name:'Refresh news',exact:true}).click();
await expect(page.getByRole('button',{name:'Refresh news',exact:true})).toBeEnabled();
await page.waitForTimeout(1000);
await page.screenshot({path:'artifacts/morning-brew-v2/'+engine+'-final-news.png'});
await page.evaluate(()=>window.scrollTo(0,0));
await page.screenshot({path:'artifacts/morning-brew-v2/'+engine+'-final-desktop.png',fullPage:true});
await page.setViewportSize({width:820,height:1000});
await page.screenshot({path:'artifacts/morning-brew-v2/'+engine+'-final-narrow.png',fullPage:true});
console.log('HORIZONTAL OVERFLOW',await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth));
await writeFile('artifacts/morning-brew-v2/browser-errors.json',JSON.stringify(errors));
console.log('PASS news refresh, desktop/narrow screenshots; page errors',errors);
await browser.close();
