apiVersion: v1
kind: ServiceAccount
metadata:
  name: audentra-portals
  labels:
    app.kubernetes.io/name: audentra-portals
    app.kubernetes.io/part-of: audentra
automountServiceAccountToken: false
