apiVersion: v1
kind: Service
metadata:
  name: audentra-portals-web
  labels:
    app.kubernetes.io/name: audentra-portals
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: audentra
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: audentra-portals
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: http
