import { test, expect } from '@playwright/test';

// Visible demo authentication and UI actions only. This validates the approved
// mock integration, not backend document processing or message delivery.
test.use({ viewport: { width: 1440, height: 900 } });
test('approved Task Board preserves the staff demo and portal navigation', async ({ page, context }, testInfo) => {
  test.setTimeout(180_000);
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await page.getByRole('link').filter({ hasText: 'Staff portal' }).click();
  await page.getByRole('button', { name: /Vivian Hale/ }).click();
  await page.locator('.staff-sidebar').getByRole('button', { name: /^Task board/ }).click();
  const board = page.frameLocator('#approved-task-board');
  await expect(board.locator('.task-card')).toHaveCount(19);
  expect(await page.locator('#approved-task-board').boundingBox()).toMatchObject({ x: 0, y: 0, width: 1440, height: 900 });
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
  await board.locator('body').evaluate(() => document.fonts.ready);
  await page.screenshot({ path: testInfo.outputPath('board-1440.png') });
  await board.locator('[data-action="toggle-nav"]').click();
  await expect(board.locator('.nav-tree')).toBeHidden();
  await board.locator('[data-action="toggle-nav"]').click();
  await board.locator('[data-space="en"]').click();
  await board.locator('[data-space="en"]').click();
  await board.locator('[data-board="en-docs"]').click();
  await board.getByRole('textbox', { name: 'Search this board' }).fill('Maya');
  await expect(board.locator('.task-card')).toHaveCount(1);
  await board.locator('[data-action="clear-filters"]').click();
  await board.locator('[data-view="list"]').click();
  await expect(board.locator('.task-list')).toBeVisible();
  await board.locator('[data-view="board"]').click();
  await board.locator('[data-task="ENR-184"]').click();
  await expect(board.locator('[data-field-row]')).toHaveCount(20);
  await expect(board.locator('[data-action="approve-document"]')).toBeDisabled();
  await expect(board.locator('.requirement-link')).toBeInViewport();
  await page.screenshot({ path: testInfo.outputPath('review-1440.png') });
  await page.setViewportSize({ width: 1920, height: 1080 });
  await page.screenshot({ path: testInfo.outputPath('review-1920.png') });
  await page.setViewportSize({ width: 1440, height: 900 });
  await board.locator('[data-evidence-link="graduation"]').click();
  await expect(board.locator('.pdf-tools')).toContainText('Page 2');
  await board.locator('.document-sheet [data-evidence="graduation"] .annotation').click();
  await expect(board.locator('#field-graduation')).toHaveClass(/focused-field/);
  await board.locator('[data-detail-tab="activity"]').click();
  await board.locator('[data-activity="communication"]').click();
  await expect(board.locator('.activity-stream')).toContainText('We received your transcript');
  await board.locator('[data-activity="comment"]').click();
  await board.getByRole('textbox', { name: 'Write a comment' }).fill('Portal integration review: identity checked against the transcript.');
  await board.getByRole('button', { name: 'Post comment', exact: true }).click();
  await expect(board.locator('.activity-stream')).toContainText('Portal integration review');
  await board.locator('[data-detail-tab="workflow"]').click();
  await expect(board.locator('.workflow-svg')).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath('workflow.png') });
  await board.locator('[data-detail-tab="workspace"]').click();
  await board.locator('[data-review-accept="name"]').click();
  await board.locator('[data-review-correction="graduation"]').click();
  await board.getByRole('button', { name: 'Save correction', exact: true }).click();
  await expect(board.locator('.detail-meta')).not.toContainText('Awaiting Correction');
  await board.getByRole('textbox', { name: 'Correction reason' }).fill('Please provide the final transcript confirming the awarded diploma.');
  await board.getByRole('button', { name: 'Save correction', exact: true }).click();
  await expect(board.locator('.detail-meta')).toContainText('Awaiting Correction');
  await board.locator('[data-detail-tab="activity"]').click();
  await board.locator('[data-activity="history"]').click();
  await expect(board.locator('.activity-stream')).toContainText('Awaiting Correction');
  await board.locator('[data-detail-tab="workspace"]').click();
  await board.locator('[data-action="transition:resubmitted"]').click();
  await board.locator('[data-action="process-document"]').click();
  await board.locator('[data-action="approve-document"]').click();
  await expect(board.locator('.detail-meta')).toContainText('Completed');
  await board.locator('[data-action="close-task"]').click();
  await expect(board.locator('[data-column="completed"] [data-task="ENR-184"]')).toBeVisible();
  await page.reload();
  await expect(board.locator('[data-column="completed"] [data-task="ENR-184"]')).toBeVisible();
  await board.locator('[data-board="en-requests"]').click();
  await board.locator('[data-task="ENR-088"]').click();
  await expect(board.locator('#request-guidance')).toBeInViewport();
  await page.screenshot({ path: testInfo.outputPath('student-request.png') });
  await board.locator('[data-request-action="checks"]').click();
  await board.locator('[data-request-action="coordinate"]').click();
  await board.getByRole('button', { name: 'Send guidance', exact: true }).click();
  await expect(board.locator('.detail-meta')).toContainText('Awaiting Resolution');
  await board.locator('[data-action="show-resolution-rule"]').click();
  await board.locator('[data-simulate="api"]').click();
  await expect(board.locator('.detail-meta')).toContainText('Completed');
  await board.locator('[data-action="close-task"]').click();
  await board.locator('[data-board="en-outreach"]').click();
  await board.locator('[data-task="ENR-431"]').click();
  await expect(board.locator('.conversation')).toContainText('afternoon');
  await board.locator('[data-action="close-task"]').click();
  await board.locator('[data-board="fa-payments"]').click();
  await board.locator('[data-task="FIN-312"]').click();
  await expect(board.locator('.payment-summary')).toContainText('$4,800.00');
  await board.locator('[data-action="close-task"]').click();
  await board.locator('[data-board="en-docs"]').click();
  await board.locator('[data-task="ENR-216"]').click();
  await expect(board.locator('#review-mode')).toHaveValue('manual');
  await expect(board.locator('[data-document-value]')).toHaveCount(20);
  await board.locator('[data-action="close-task"]').click();
  await board.locator('[data-action="shell:Morning Brew"]').click();
  await expect(page.locator('#approved-task-board')).toHaveCount(0);
  await expect(page).toHaveURL(/#morning_brew$/);
  await page.locator('.staff-sidebar').getByRole('button', { name: /^Task board/ }).click();
  await expect(board.locator('[data-column="completed"] [data-task="ENR-184"]')).toBeVisible();
  await context.grantPermissions(['clipboard-read', 'clipboard-write'], { origin: new URL(page.url()).origin });
  await board.locator('[data-task="ENR-184"]').click();
  await board.locator('[data-action="copy-task"]').click();
  await expect(board.locator('#toast')).toContainText('link copied');
  const linked = await page.evaluate(() => navigator.clipboard.readText());
  expect(linked).toContain('actionTask=ENR-184');
  expect(linked).toMatch(/#tasks$/);
  await page.goto(linked);
  await expect(board.locator('#task-title')).toContainText('transcript');
  await expect(board.locator('.detail-meta')).toContainText('Completed');
  expect(errors).toEqual([]);
});
