/** Student header/summary layout sweep; reads demo records without submitting changes. */
import {chromium} from '@playwright/test';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const browser=await chromium.launch();const phase=process.env.PHASE||'after';const results=process.env.ONLY_FINANCIALS?JSON.parse(await fs.readFile(`artifacts/ui-refresh/frame-${phase}/results.json`,'utf8')).filter(x=>!x.route.startsWith('/financials')):[];const out=`artifacts/ui-refresh/frame-${phase}`;await fs.mkdir(out,{recursive:true});
try{const context=await browser.newContext({storageState:'artifacts/ui-refresh/session.json',reducedMotion:'reduce'});const page=await context.newPage();for(const width of [1440,1280,390])for(const route of ['/enrollment','/appointments','/classrooms','/health','/housing','/campus-life','/profile','/help','/financials','/financials/payments','/financials/aid','/financials/expenses']){
 if(process.env.ONLY_FINANCIALS&&!route.startsWith('/financials'))continue;
 await page.setViewportSize({width,height:width===390?844:1000});await page.goto('http://localhost:3000'+route);const root=route.startsWith('/financials')?page.frameLocator('iframe'):page;await root.locator('.page-hero').waitFor({timeout:60000});if(['/enrollment','/classrooms','/health','/housing'].includes(route)||route.startsWith('/financials'))await root.locator('.page-summary').waitFor({timeout:60000});if(route.startsWith('/financials'))await root.locator('#sum-figure').filter({hasText:/\$/}).waitFor({timeout:60000});await page.waitForTimeout(800);
 const data=await root.locator('.page-hero').evaluate(hero=>{const summary=hero.parentElement.querySelector('.page-summary');const read=e=>{if(!e)return null;const s=getComputedStyle(e),r=e.getBoundingClientRect();return {class:e.className,text:e.innerText?.slice(0,180),x:r.x,y:r.y,w:r.width,h:r.height,font:s.fontSize,line:s.lineHeight,weight:s.fontWeight,padding:s.padding,margin:s.margin,display:s.display,cols:s.gridTemplateColumns}};return {hero:read(hero),title:read(hero.querySelector('h1')),lede:read(hero.querySelector('.hero-lede')),summary:read(summary),body:read(summary?.querySelector('.summary-main')),figure:read(summary?.querySelector('.summary-figure-copy strong,.summary-figure .big')),advisor:read(summary?.querySelector('.advisor-bar')),overlap:summary?hero.getBoundingClientRect().bottom-summary.getBoundingClientRect().top:null,overflow:document.documentElement.scrollWidth>innerWidth}});
 if(phase==='after'){assert.equal(data.title.font,width===390?'27px':'34px');assert.equal(data.lede.font,width===390?'12.5px':'13.5px');assert.equal(data.overflow,false);if(data.summary){assert.equal(data.overlap,width===390?14:20);assert.equal(data.body.padding,width===390?'18px':'24px');} }
 results.push({route,width,...data});if(width!==1280)await page.screenshot({path:`${out}/${route.slice(1).replaceAll('/','-')}-${width}.png`,fullPage:false});console.log(route,width,data.hero.h,data.title.font,data.lede.font,data.overlap,data.body?.h);await fs.writeFile(out+'/results.json',JSON.stringify(results,null,2));
}}finally{await browser.close()}
