import type {
  BrewChange,
  BrewEmail,
  BrewInsight,
  BrewKpi,
  BrewMeeting,
  BrewNewsItem,
  BrewPriority,
  BrewQuickLink,
} from "./types";

/**
 * Presentation corpus for Morning Brew.
 *
 * Everything here is believable synthetic content for Aster University's Fall
 * 2026 cycle. Numbers are internally consistent across insights, KPI frames,
 * and detail drill-downs so the briefing holds up when a reader clicks through.
 */

/* ----------------------------------------------------------------- insights */

export const BREW_INSIGHTS: BrewInsight[] = [
  {
    id: "commuter-deposit-pace",
    topic: "admissions",
    label: "Enrollment signal",
    title: "Commuter student deposit pace is slowing",
    severity: "high",
    summary:
      "Deposit rate for accepted commuter students declined 6.4% in the last 7 days.",
    projection:
      "If this continues, we project 82 fewer deposits by May 31 (~$1.6M in tuition).",
    impactLabel: "Potential Impact",
    impact: [
      { label: "−$1.8M", tone: "negative" },
      { label: "−92 Enrolled Students", tone: "negative" },
    ],
    recommendedAction:
      "Launch targeted outreach to 312 high-probability students with incomplete financial aid.",
    impactLevel: "High",
    confidence: 85,
    source: "modeled",
    destination: "outreach",
    detail: {
      narrative: [
        "Commuter admits have historically deposited 4–6 days after their aid package is finalized. That gap widened to 11 days over the last two weeks, and the deposit curve flattened with it.",
        "The slowdown is not a demand problem. Portal sessions, aid-offer opens, and campus-visit registrations for this segment are all at or above last cycle. What changed is how long a student waits between seeing their offer and being able to act on it.",
        "312 commuter admits are sitting behind an incomplete aid file. They represent the highest-probability recoverable deposits in the funnel — the model gives them a 61% conversion rate if their file clears inside seven days, and 24% after that.",
      ],
      drivers: [
        { label: "Verification wait", value: "11.2 days", note: "Up from 6.1 days two weeks ago" },
        { label: "Aid-incomplete admits", value: "312", note: "Commuter segment only" },
        { label: "Offer-to-deposit gap", value: "+5.1 days", note: "Versus the same week last cycle" },
        { label: "Portal engagement", value: "+4.8%", note: "Demand is holding — friction is the issue" },
      ],
      trend: [
        { label: "Apr 6", value: 44.2 },
        { label: "Apr 13", value: 43.8 },
        { label: "Apr 20", value: 43.1 },
        { label: "Apr 27", value: 42.4 },
        { label: "May 4", value: 41.0 },
        { label: "May 11", value: 39.6 },
        { label: "May 18", value: 38.2 },
      ],
      trendUnit: "Commuter deposit rate (%)",
      actions: [
        {
          title: "Clear the 312 aid-incomplete commuter files first",
          detail: "Re-sequence the verification queue by deposit probability instead of submission date.",
          owner: "Financial Aid Operations",
          due: "Today",
        },
        {
          title: "Send the two-step commuter nudge",
          detail: "One message naming the exact missing document, one confirming the deposit deadline.",
          owner: "Enrollment Marketing",
          due: "Tomorrow",
        },
        {
          title: "Open two same-day aid appointment blocks",
          detail: "Afternoon slots convert best for commuter families who work daytime hours.",
          owner: "Student Financial Services",
          due: "This week",
        },
      ],
      students: [
        { name: "Maya Kim", program: "Health Sciences", note: "Verification docs outstanding for 9 days", risk: "critical" },
        { name: "Mateo Johnson", program: "Business Administration", note: "Aid offer opened 4 times, no deposit", risk: "high" },
        { name: "Lucas Brown", program: "Psychology", note: "Appeal submitted, awaiting committee", risk: "high" },
        { name: "Amara Okafor", program: "Nursing", note: "Missing signed tax transcript", risk: "medium" },
      ],
      evidence: [
        "Modeled from workspace journey progress, aid file status, and deposit timestamps.",
        "Conversion probabilities come from the last three Fall cycles for the commuter segment.",
        "Dollar impact uses the current average net tuition of $19,600 per enrolled commuter.",
      ],
    },
  },
  {
    id: "verification-backlog",
    topic: "financial_aid",
    label: "Financial aid",
    title: "Financial aid verification backlog increasing",
    severity: "medium",
    summary: "Verification cases are up 18% vs last week, driving delays in aid packages.",
    projection: "312 students are at risk of delaying their deposit.",
    impactLabel: "Potential Impact",
    impact: [{ label: "−36 Enrolled Students", tone: "negative" }],
    recommendedAction: "Add 2 temporary reviewers and prioritize commuter and transfer cases.",
    impactLevel: "High",
    confidence: 75,
    source: "workspace",
    destination: "tasks",
    detail: {
      narrative: [
        "The queue holds 468 open verification cases against a topic that clears roughly 95 per day at full staffing. Two reviewers are on leave through the end of the month, which puts real throughput closer to 72.",
        "At current pace the backlog clears on June 14 — eleven days after the deposit deadline. Every day of drift moves students out of the high-conversion window.",
        "Adding two temporary reviewers restores throughput to 96/day and pulls the clear date back to May 29, ahead of the deadline. The cost is roughly $9,400 in temporary staffing against $1.8M of exposed net tuition.",
      ],
      drivers: [
        { label: "Open cases", value: "468", note: "Up 18% week over week" },
        { label: "Daily clear rate", value: "72", note: "Down from 95 at full staffing" },
        { label: "Median wait", value: "11.2 days", note: "Service standard is 5 days" },
        { label: "Deadline exposure", value: "12 files", note: "Deadlines inside the next 7 days" },
      ],
      trend: [
        { label: "Apr 20", value: 288 },
        { label: "Apr 27", value: 305 },
        { label: "May 4", value: 341 },
        { label: "May 11", value: 372 },
        { label: "May 18", value: 397 },
        { label: "May 25", value: 468 },
      ],
      trendUnit: "Open verification cases",
      actions: [
        {
          title: "Approve two temporary reviewers for three weeks",
          detail: "Restores throughput to 96 files per day and clears the backlog before the deposit deadline.",
          owner: "You",
          due: "Today",
        },
        {
          title: "Re-sequence the queue by deposit probability",
          detail: "Commuter and transfer cases first — they carry the largest recoverable yield.",
          owner: "Verification Team Lead",
          due: "Today",
        },
        {
          title: "Auto-request the top three missing documents",
          detail: "Tax transcripts, verification worksheets, and identity affidavits cover 78% of holds.",
          owner: "Financial Aid Operations",
          due: "This week",
        },
      ],
      students: [
        { name: "Maya Kim", program: "Health Sciences", note: "Selected for V1 verification, 9 days open", risk: "critical" },
        { name: "Sofia Martinez", program: "Biology", note: "Conflicting income data, needs review", risk: "high" },
        { name: "Ethan Nguyen", program: "Engineering", note: "Identity verification incomplete", risk: "medium" },
      ],
      evidence: [
        "Case counts and wait times come from your live Audentra workspace queue.",
        "Throughput modeling assumes the current reviewer roster and historical clear rates.",
        "Staffing cost is an estimate for demonstration and is not a procurement quote.",
      ],
    },
  },
  {
    id: "transfer-volume",
    topic: "admissions",
    label: "Positive signal",
    title: "Transfer application volume trending above target",
    severity: "positive",
    summary:
      "Transfer applications are up 14% vs last year and 9% above target pace.",
    projection: "Strong interest in Business and Health Sciences programs.",
    impactLabel: "Potential Impact",
    impact: [
      { label: "+$1.2M", tone: "positive" },
      { label: "+48 Enrolled Students", tone: "positive" },
    ],
    recommendedAction: "Increase admitted student events for transfer prospects at top feeder schools.",
    impactLevel: "Medium",
    confidence: 80,
    source: "modeled",
    destination: "students",
    detail: {
      narrative: [
        "Transfer applications reached 1,412 for the cycle, 14% ahead of last year and 9% above the pace needed to hit the 1,850 target.",
        "Two programs account for two thirds of the lift: Business Administration (+186) and Health Sciences (+142). Both draw heavily from three community college partners inside a 40-mile radius.",
        "Transfer admits also deposit faster than first-year admits — a median of 6 days versus 14 — so converting this volume protects the cycle earlier than any first-year play.",
      ],
      drivers: [
        { label: "Transfer applications", value: "1,412", note: "+14% year over year" },
        { label: "Top feeder growth", value: "+31%", note: "Riverbend, Northview, Cascade CC" },
        { label: "Median deposit lag", value: "6 days", note: "First-year segment is 14 days" },
        { label: "Credit evaluation wait", value: "8.4 days", note: "The one friction point to watch" },
      ],
      trend: [
        { label: "Jan", value: 168 },
        { label: "Feb", value: 214 },
        { label: "Mar", value: 246 },
        { label: "Apr", value: 288 },
        { label: "May", value: 312 },
        { label: "Jun", value: 184 },
      ],
      trendUnit: "Transfer applications received",
      actions: [
        {
          title: "Add two transfer admitted-student events",
          detail: "Evening sessions at Riverbend and Northview convert best for working students.",
          owner: "Transfer Admissions",
          due: "This week",
        },
        {
          title: "Fast-track credit evaluations for deposited transfers",
          detail: "The 8.4-day evaluation wait is the only friction point in an otherwise healthy segment.",
          owner: "Registrar",
          due: "This week",
        },
        {
          title: "Pre-package aid for transfer admits",
          detail: "Transfers who see an aid number at admission deposit at nearly twice the rate.",
          owner: "Financial Aid",
          due: "Next week",
        },
      ],
      students: [
        { name: "Jordan Garcia", program: "Computer Science", note: "Transfer admit, credit evaluation pending", risk: "medium" },
        { name: "Noah Williams", program: "Communications", note: "Deposited, awaiting orientation registration", risk: "medium" },
      ],
      evidence: [
        "Application counts are modeled from the Fall 2026 funnel snapshot.",
        "Feeder-school growth compares the same week across the last two cycles.",
        "Revenue impact assumes the current transfer net tuition average of $17,300.",
      ],
    },
  },
  {
    id: "appeal-turnaround",
    topic: "financial_aid",
    label: "Service standard",
    title: "Aid appeal turnaround is drifting past the five-day promise",
    severity: "high",
    summary: "Median appeal decision time reached 7.8 days, up from 4.6 days in April.",
    projection: "41 families are currently waiting past the published service standard.",
    impactLabel: "Potential Impact",
    impact: [
      { label: "−$0.6M", tone: "negative" },
      { label: "41 families waiting", tone: "neutral" },
    ],
    recommendedAction: "Move the appeal committee to twice-weekly sessions through the deposit deadline.",
    impactLevel: "Medium",
    confidence: 78,
    source: "modeled",
    destination: "tasks",
    detail: {
      narrative: [
        "The appeal committee meets Thursdays. With 27 appeals arriving each week and 22 decided per session, the queue has been growing since the first week of May.",
        "Appeals correlate strongly with deposit intent: 74% of families who appeal go on to deposit when the decision lands inside five days. That drops to 39% past ten days.",
        "A second weekly session through June 5 clears the standing queue and returns the median to 4.2 days without adding headcount.",
      ],
      drivers: [
        { label: "Median decision time", value: "7.8 days", note: "Service standard is 5 days" },
        { label: "Appeals in queue", value: "41", note: "All past the published standard" },
        { label: "Weekly arrival rate", value: "27", note: "Committee decides 22 per session" },
        { label: "Approval rate", value: "81%", note: "Consistent with prior cycles" },
      ],
      trend: [
        { label: "Apr 6", value: 4.2 },
        { label: "Apr 13", value: 4.6 },
        { label: "Apr 20", value: 5.4 },
        { label: "Apr 27", value: 6.1 },
        { label: "May 4", value: 6.9 },
        { label: "May 11", value: 7.8 },
      ],
      trendUnit: "Median appeal decision (days)",
      actions: [
        {
          title: "Add a Tuesday committee session through June 5",
          detail: "Two sessions per week clear the standing queue in eleven days.",
          owner: "You",
          due: "Today",
        },
        {
          title: "Pre-screen appeals with complete documentation",
          detail: "Roughly a third are straightforward approvals that do not need full committee time.",
          owner: "Appeals Coordinator",
          due: "This week",
        },
      ],
      students: [
        { name: "Lucas Brown", program: "Psychology", note: "Appeal filed 12 days ago, no decision", risk: "high" },
        { name: "Sofia Martinez", program: "Biology", note: "Income change appeal, documents complete", risk: "high" },
      ],
      evidence: [
        "Appeal timing is derived from your workspace task history.",
        "Conversion rates by decision speed are modeled from the last three cycles.",
      ],
    },
  },
  {
    id: "melt-risk",
    topic: "student_success",
    label: "Retention watch",
    title: "Summer melt risk is concentrating in first-generation admits",
    severity: "high",
    summary:
      "Deposited first-generation students are 2.3x more likely to miss orientation registration.",
    projection: "68 deposited students show two or more melt signals.",
    impactLabel: "Potential Impact",
    impact: [
      { label: "−$1.3M", tone: "negative" },
      { label: "−68 Enrolled Students", tone: "negative" },
    ],
    recommendedAction: "Assign a named success coach to every first-generation deposit before June 15.",
    impactLevel: "High",
    confidence: 82,
    source: "workspace",
    destination: "students",
    detail: {
      narrative: [
        "Melt signals are stacking earlier than usual. 68 deposited students carry two or more of: no orientation registration, no housing action, unopened advising outreach, and an unresolved balance.",
        "First-generation students make up 31% of the deposited class but 58% of that flagged group. The pattern is not academic readiness — it is navigation.",
        "Cohorts with a named coach assigned before June 15 melted at 4.1% last cycle versus 11.8% for unassigned deposits.",
      ],
      drivers: [
        { label: "Flagged deposits", value: "68", note: "Two or more melt signals" },
        { label: "First-generation share", value: "58%", note: "Of the flagged group" },
        { label: "No orientation registration", value: "142", note: "Across all deposits" },
        { label: "Coach coverage", value: "46%", note: "Of first-generation deposits" },
      ],
      trend: [
        { label: "Week 1", value: 18 },
        { label: "Week 2", value: 27 },
        { label: "Week 3", value: 34 },
        { label: "Week 4", value: 49 },
        { label: "Week 5", value: 61 },
        { label: "Week 6", value: 68 },
      ],
      trendUnit: "Deposits with 2+ melt signals",
      actions: [
        {
          title: "Assign coaches to all first-generation deposits",
          detail: "Coverage is 46% today. Full coverage before June 15 is the single highest-leverage move.",
          owner: "Student Success",
          due: "This week",
        },
        {
          title: "Run an orientation registration sweep",
          detail: "142 deposited students have not registered. A one-touch call clears roughly 60%.",
          owner: "Orientation Team",
          due: "This week",
        },
      ],
      students: [
        { name: "Noah Williams", program: "Communications", note: "No orientation registration, balance open", risk: "high" },
        { name: "Ethan Nguyen", program: "Engineering", note: "Three unopened advising messages", risk: "high" },
        { name: "Sofia Martinez", program: "Biology", note: "Housing action not started", risk: "medium" },
      ],
      evidence: [
        "Melt signals are computed from live workspace journey and engagement data.",
        "Comparison melt rates come from the prior two Fall cohorts.",
      ],
    },
  },
  {
    id: "housing-blockers",
    topic: "housing",
    label: "Operations",
    title: "Deposit-paid students are stalling before room selection",
    severity: "medium",
    summary: "23 students paid a deposit but cannot enter room selection.",
    projection: "Access and prerequisite mismatches explain 19 of the 23 cases.",
    impactLabel: "Potential Impact",
    impact: [{ label: "23 students blocked", tone: "neutral" }],
    recommendedAction: "Clear the prerequisite mismatch in the housing portal before the next selection window.",
    impactLevel: "Medium",
    confidence: 90,
    source: "modeled",
    destination: "campus_life",
    detail: {
      narrative: [
        "Room selection opened to 1,190 deposited students. 23 of them cannot proceed — not because they have not tried, but because the portal is checking a prerequisite their record does not yet reflect.",
        "Nineteen cases trace to a single rule: the housing portal requires a posted immunization record, and those records are still queued in the health center import.",
        "This is an operational fix, not an outreach problem. Sending another reminder to these students would be the wrong move.",
      ],
      drivers: [
        { label: "Blocked students", value: "23", note: "All have paid a deposit" },
        { label: "Immunization import lag", value: "19 cases", note: "Health center batch pending" },
        { label: "Access errors", value: "4 cases", note: "Portal account provisioning" },
        { label: "Selection window closes", value: "6 days", note: "Next window opens July 8" },
      ],
      trend: [
        { label: "Mon", value: 9 },
        { label: "Tue", value: 14 },
        { label: "Wed", value: 17 },
        { label: "Thu", value: 21 },
        { label: "Fri", value: 23 },
      ],
      trendUnit: "Blocked deposit-paid students",
      actions: [
        {
          title: "Run the health center immunization import",
          detail: "Clears 19 of 23 cases without any student contact.",
          owner: "Housing Operations",
          due: "Today",
        },
        {
          title: "Re-provision four portal accounts",
          detail: "Manual account fix, then a single confirmation message.",
          owner: "IT Service Desk",
          due: "Today",
        },
      ],
      students: [
        { name: "Amara Okafor", program: "Nursing", note: "Immunization record pending import", risk: "medium" },
        { name: "Mateo Johnson", program: "Business Administration", note: "Portal account not provisioned", risk: "medium" },
      ],
      evidence: [
        "Blocked-student counts come from live workspace journey blockers.",
        "Root-cause grouping is modeled for this demonstration.",
      ],
    },
  },
  {
    id: "transcript-holds",
    topic: "registrar",
    label: "Records",
    title: "Transcript evaluation queue is delaying transfer credit decisions",
    severity: "medium",
    summary: "Median credit evaluation is 8.4 days against a 5-day standard.",
    projection: "204 transfer admits are waiting on a credit decision.",
    impactLabel: "Potential Impact",
    impact: [{ label: "204 transfer admits waiting", tone: "neutral" }],
    recommendedAction: "Batch-evaluate the three feeder schools that account for 61% of the queue.",
    impactLevel: "Medium",
    confidence: 76,
    source: "modeled",
    destination: "academics",
    detail: {
      narrative: [
        "Transfer admits will not deposit against an unknown credit total. 204 are waiting, and the median evaluation now runs 8.4 days.",
        "Three feeder schools — Riverbend, Northview, and Cascade — account for 61% of the queue and share nearly identical course maps.",
        "Batch evaluation against a stored articulation map would clear that 61% in a single pass instead of one record at a time.",
      ],
      drivers: [
        { label: "Evaluations pending", value: "204", note: "All transfer admits" },
        { label: "Median turnaround", value: "8.4 days", note: "Standard is 5 days" },
        { label: "Top-3 feeder share", value: "61%", note: "Riverbend, Northview, Cascade" },
        { label: "Articulation coverage", value: "88%", note: "Of courses in the queue" },
      ],
      trend: [
        { label: "Apr 13", value: 5.1 },
        { label: "Apr 20", value: 5.8 },
        { label: "Apr 27", value: 6.6 },
        { label: "May 4", value: 7.4 },
        { label: "May 11", value: 8.4 },
      ],
      trendUnit: "Median credit evaluation (days)",
      actions: [
        {
          title: "Batch-evaluate the three top feeder schools",
          detail: "88% articulation coverage means most of the queue can clear automatically.",
          owner: "Registrar",
          due: "This week",
        },
      ],
      students: [
        { name: "Jordan Garcia", program: "Computer Science", note: "Riverbend transfer, 46 credits pending", risk: "medium" },
      ],
      evidence: ["Queue depth and turnaround are modeled for this demonstration."],
    },
  },
];

/* --------------------------------------------------------------------- kpis */

export const BREW_KPIS: BrewKpi[] = [
  {
    id: "applications",
    topic: "admissions",
    label: "Applications",
    icon: "◫",
    format: "int",
    source: "modeled",
    frames: {
      yesterday: {
        numeric: 412,
        window: "Received yesterday",
        delta: "3.2%",
        direction: "up",
        favorable: true,
        comparison: "vs yesterday",
        points: [318, 344, 361, 352, 379, 388, 401, 399, 412],
        target: "Pace 480/day",
        targetProgress: 86,
        note: "Strongest single day since the May 1 priority deadline.",
      },
      week: {
        numeric: 2180,
        window: "Received this week",
        delta: "8.4%",
        direction: "up",
        favorable: true,
        comparison: "vs last week",
        points: [1740, 1812, 1866, 1948, 1902, 2044, 2110, 2180],
        target: "Pace 2,540/wk",
        targetProgress: 86,
        note: "Transfer applications are carrying most of the weekly lift.",
      },
      month: {
        numeric: 6940,
        window: "Received this month",
        delta: "12.1%",
        direction: "up",
        favorable: true,
        comparison: "vs last month",
        points: [4880, 5240, 5610, 5880, 6190, 6420, 6710, 6940],
        target: "Plan 7,600",
        targetProgress: 91,
        note: "May is tracking to be the second-largest application month of the cycle.",
      },
      year: {
        numeric: 14782,
        window: "Cycle to date",
        delta: "5.6%",
        direction: "up",
        favorable: true,
        comparison: "vs last year",
        points: [9200, 10400, 11350, 12080, 12940, 13610, 14220, 14782],
        target: "Target 20,000",
        targetProgress: 74,
        note: "Ahead of last cycle at the same point by 784 applications.",
      },
    },
    detail: {
      definition:
        "Completed applications received for the Fall 2026 entering class, deduplicated and excluding withdrawn records.",
      owner: "Admissions Operations · Dana Whitfield",
      updated: "7:30 AM ET",
      segments: [
        { label: "First-year", value: "11,486", delta: "+3.1%", favorable: true },
        { label: "Transfer", value: "1,412", delta: "+14.0%", favorable: true },
        { label: "Commuter", value: "3,884", delta: "+1.2%", favorable: true },
        { label: "Out-of-state", value: "4,208", delta: "−2.4%", favorable: false },
      ],
      history: [
        { label: "Oct", value: 1180, benchmark: 1120 },
        { label: "Nov", value: 2240, benchmark: 2180 },
        { label: "Dec", value: 3610, benchmark: 3480 },
        { label: "Jan", value: 6820, benchmark: 6540 },
        { label: "Feb", value: 9240, benchmark: 8890 },
        { label: "Mar", value: 11360, benchmark: 10820 },
        { label: "Apr", value: 13100, benchmark: 12480 },
        { label: "May", value: 14782, benchmark: 13998 },
      ],
      historyUnit: "Cumulative applications",
      notes: [
        "Benchmark line is the same point in the Fall 2025 cycle.",
        "Volume is healthy; conversion — not applications — is the constraint this cycle.",
      ],
    },
  },
  {
    id: "admits",
    topic: "admissions",
    label: "Admits",
    icon: "✓",
    format: "int",
    source: "modeled",
    frames: {
      yesterday: {
        numeric: 168,
        window: "Admitted yesterday",
        delta: "2.8%",
        direction: "up",
        favorable: true,
        comparison: "vs yesterday",
        points: [132, 141, 149, 144, 158, 161, 163, 168],
        target: "Pace 190/day",
        targetProgress: 88,
        note: "Committee cleared the Health Sciences reading queue.",
      },
      week: {
        numeric: 902,
        window: "Admitted this week",
        delta: "4.1%",
        direction: "up",
        favorable: true,
        comparison: "vs last week",
        points: [742, 768, 804, 796, 838, 866, 884, 902],
        target: "Pace 1,020/wk",
        targetProgress: 88,
        note: "Reading capacity is the current limit, not applicant quality.",
      },
      month: {
        numeric: 2845,
        window: "Admitted this month",
        delta: "1.6%",
        direction: "down",
        favorable: false,
        comparison: "vs last month",
        points: [2980, 2946, 2918, 2890, 2874, 2861, 2852, 2845],
        target: "Plan 3,050",
        targetProgress: 93,
        note: "Two readers on leave slowed the May committee cadence.",
      },
      year: {
        numeric: 6125,
        window: "Cycle to date",
        delta: "2.8%",
        direction: "up",
        favorable: true,
        comparison: "vs last year",
        points: [2140, 2880, 3520, 4180, 4740, 5310, 5760, 6125],
        target: "Target 8,500",
        targetProgress: 72,
        note: "Admit rate is holding at 41.4%, in line with the enrollment plan.",
      },
    },
    detail: {
      definition:
        "Students offered admission for Fall 2026, including conditional and rolling decisions.",
      owner: "Admissions Committee · Dana Whitfield",
      updated: "7:30 AM ET",
      segments: [
        { label: "First-year", value: "4,918", delta: "+2.2%", favorable: true },
        { label: "Transfer", value: "1,207", delta: "+8.6%", favorable: true },
        { label: "Commuter", value: "1,846", delta: "+0.4%", favorable: true },
        { label: "Out-of-state", value: "1,684", delta: "−3.1%", favorable: false },
      ],
      history: [
        { label: "Oct", value: 210, benchmark: 240 },
        { label: "Nov", value: 640, benchmark: 690 },
        { label: "Dec", value: 1180, benchmark: 1220 },
        { label: "Jan", value: 2240, benchmark: 2210 },
        { label: "Feb", value: 3410, benchmark: 3320 },
        { label: "Mar", value: 4620, benchmark: 4480 },
        { label: "Apr", value: 5480, benchmark: 5310 },
        { label: "May", value: 6125, benchmark: 5958 },
      ],
      historyUnit: "Cumulative admits",
      notes: [
        "Admit rate of 41.4% is within the ±2 point band the enrollment plan allows.",
        "Reading capacity, not applicant quality, is what slowed the May pace.",
      ],
    },
  },
  {
    id: "deposits",
    topic: "admissions",
    label: "Deposit Paid",
    icon: "$",
    format: "int",
    source: "modeled",
    frames: {
      yesterday: {
        numeric: 64,
        window: "Deposits yesterday",
        delta: "1.1%",
        direction: "down",
        favorable: false,
        comparison: "vs yesterday",
        points: [78, 74, 71, 76, 69, 67, 65, 64],
        target: "Pace 74/day",
        targetProgress: 86,
        note: "Commuter deposits account for the entire day-over-day decline.",
      },
      week: {
        numeric: 338,
        window: "Deposits this week",
        delta: "4.2%",
        direction: "down",
        favorable: false,
        comparison: "vs last week",
        points: [402, 388, 376, 369, 358, 351, 344, 338],
        target: "Pace 390/wk",
        targetProgress: 87,
        note: "Sixth consecutive week of softening deposit flow.",
      },
      month: {
        numeric: 1126,
        window: "Deposits this month",
        delta: "2.4%",
        direction: "up",
        favorable: true,
        comparison: "vs last month",
        points: [860, 928, 976, 1014, 1052, 1080, 1104, 1126],
        target: "Plan 1,240",
        targetProgress: 91,
        note: "Monthly total still climbs, but the weekly slope is flattening.",
      },
      year: {
        numeric: 2450,
        window: "Cycle to date",
        delta: "1.1%",
        direction: "down",
        favorable: false,
        comparison: "vs last year",
        points: [420, 720, 1010, 1340, 1680, 1980, 2240, 2450],
        target: "Target 3,200",
        targetProgress: 77,
        note: "27 deposits behind the same point last cycle.",
      },
    },
    detail: {
      definition:
        "Enrollment deposits received and posted for Fall 2026, net of refunds and cancellations.",
      owner: "Student Financial Services · Priya Shah",
      updated: "7:30 AM ET",
      segments: [
        { label: "Residential", value: "1,468", delta: "+2.8%", favorable: true },
        { label: "Commuter", value: "612", delta: "−6.4%", favorable: false },
        { label: "Transfer", value: "284", delta: "+11.2%", favorable: true },
        { label: "Out-of-state", value: "486", delta: "−1.9%", favorable: false },
      ],
      history: [
        { label: "Jan", value: 210, benchmark: 224 },
        { label: "Feb", value: 486, benchmark: 502 },
        { label: "Mar", value: 940, benchmark: 968 },
        { label: "Apr", value: 1624, benchmark: 1642 },
        { label: "May 4", value: 1980, benchmark: 1996 },
        { label: "May 11", value: 2180, benchmark: 2204 },
        { label: "May 18", value: 2330, benchmark: 2362 },
        { label: "May 25", value: 2450, benchmark: 2477 },
      ],
      historyUnit: "Cumulative deposits",
      notes: [
        "The commuter segment is the entire gap. Every other segment is at or ahead of last cycle.",
        "Aid file completion is the strongest predictor of deposit timing in this cohort.",
      ],
    },
  },
  {
    id: "deposit-rate",
    topic: "admissions",
    label: "Deposit Rate",
    icon: "％",
    format: "percent",
    source: "modeled",
    frames: {
      yesterday: {
        numeric: 38.1,
        window: "Rate yesterday",
        delta: "1.4pp",
        direction: "down",
        favorable: false,
        comparison: "vs yesterday",
        points: [42.1, 41.4, 40.8, 40.2, 39.6, 39.0, 38.6, 38.1],
        target: "Target 45.0%",
        targetProgress: 85,
        note: "Single-day rate is noisy; the weekly slope is the signal.",
      },
      week: {
        numeric: 37.5,
        window: "Rate this week",
        delta: "2.1pp",
        direction: "down",
        favorable: false,
        comparison: "vs last week",
        points: [41.8, 41.0, 40.3, 39.6, 39.0, 38.4, 37.9, 37.5],
        target: "Target 45.0%",
        targetProgress: 83,
        note: "Commuter admits are converting 6.4 points below the cohort average.",
      },
      month: {
        numeric: 39.6,
        window: "Rate this month",
        delta: "0.8pp",
        direction: "down",
        favorable: false,
        comparison: "vs last month",
        points: [41.2, 40.9, 40.6, 40.4, 40.1, 39.9, 39.7, 39.6],
        target: "Target 45.0%",
        targetProgress: 88,
        note: "The monthly figure masks a sharper decline in the last ten days.",
      },
      year: {
        numeric: 40.1,
        window: "Cycle to date",
        delta: "1.7pp",
        direction: "down",
        favorable: false,
        comparison: "vs last year",
        points: [43.6, 43.1, 42.6, 42.0, 41.4, 40.9, 40.4, 40.1],
        target: "Target 45.0%",
        targetProgress: 89,
        note: "1.7 points behind last cycle — worth about 104 enrolled students.",
      },
    },
    detail: {
      definition: "Deposits divided by admits, measured on the same admit cohort window.",
      owner: "Institutional Research · Sam Oduya",
      updated: "7:30 AM ET",
      segments: [
        { label: "Residential", value: "44.8%", delta: "+0.6pp", favorable: true },
        { label: "Commuter", value: "33.2%", delta: "−6.4pp", favorable: false },
        { label: "Transfer", value: "48.1%", delta: "+2.2pp", favorable: true },
        { label: "Out-of-state", value: "28.9%", delta: "−1.1pp", favorable: false },
      ],
      history: [
        { label: "Jan", value: 43.9, benchmark: 44.6 },
        { label: "Feb", value: 43.4, benchmark: 44.2 },
        { label: "Mar", value: 42.6, benchmark: 43.8 },
        { label: "Apr", value: 41.5, benchmark: 43.1 },
        { label: "May 4", value: 40.9, benchmark: 42.6 },
        { label: "May 11", value: 40.6, benchmark: 42.3 },
        { label: "May 18", value: 40.3, benchmark: 42.0 },
        { label: "May 25", value: 40.1, benchmark: 41.8 },
      ],
      historyUnit: "Deposit rate (%)",
      notes: [
        "Every point of deposit rate is worth roughly 61 enrolled students at current admit volume.",
        "Commuter conversion explains 78% of the variance from last cycle.",
      ],
    },
  },
  {
    id: "net-tuition",
    topic: "financial_aid",
    label: "Net Tuition (Proj.)",
    icon: "▣",
    format: "currencyM",
    source: "modeled",
    frames: {
      yesterday: {
        numeric: 1.4,
        window: "Committed yesterday",
        delta: "1.3%",
        direction: "down",
        favorable: false,
        comparison: "vs yesterday",
        points: [1.72, 1.66, 1.58, 1.61, 1.52, 1.48, 1.44, 1.4],
        target: "Pace $1.6M/day",
        targetProgress: 88,
        note: "Tracks the deposit slowdown one day behind.",
      },
      week: {
        numeric: 7.6,
        window: "Committed this week",
        delta: "3.8%",
        direction: "down",
        favorable: false,
        comparison: "vs last week",
        points: [9.1, 8.8, 8.5, 8.3, 8.0, 7.9, 7.7, 7.6],
        target: "Pace $8.4M/wk",
        targetProgress: 90,
        note: "Discount rate held steady, so this is volume — not price.",
      },
      month: {
        numeric: 24.8,
        window: "Committed this month",
        delta: "2.1%",
        direction: "up",
        favorable: true,
        comparison: "vs last month",
        points: [18.4, 19.9, 21.1, 22.2, 23.1, 23.8, 24.4, 24.8],
        target: "Plan $27.5M",
        targetProgress: 90,
        note: "Still adding revenue, just more slowly than plan.",
      },
      year: {
        numeric: 98.4,
        window: "Projected, full cycle",
        delta: "5.2%",
        direction: "up",
        favorable: true,
        comparison: "vs last year",
        points: [72.4, 78.1, 82.6, 86.9, 90.4, 93.6, 96.2, 98.4],
        target: "Target $110.0M",
        targetProgress: 89,
        note: "$11.6M below the planning target with yield as the swing factor.",
      },
    },
    detail: {
      definition:
        "Projected gross tuition less institutional aid for the Fall 2026 entering class, based on the current deposit curve.",
      owner: "Financial Aid & Budget Office · Priya Shah",
      updated: "7:30 AM ET",
      segments: [
        { label: "Residential", value: "$61.2M", delta: "+6.8%", favorable: true },
        { label: "Commuter", value: "$18.9M", delta: "−4.1%", favorable: false },
        { label: "Transfer", value: "$11.4M", delta: "+12.4%", favorable: true },
        { label: "Graduate bridge", value: "$6.9M", delta: "+1.2%", favorable: true },
      ],
      history: [
        { label: "Jan", value: 72.4, benchmark: 70.1 },
        { label: "Feb", value: 78.1, benchmark: 74.8 },
        { label: "Mar", value: 82.6, benchmark: 79.2 },
        { label: "Apr", value: 86.9, benchmark: 83.4 },
        { label: "May 4", value: 90.4, benchmark: 86.6 },
        { label: "May 11", value: 93.6, benchmark: 89.4 },
        { label: "May 18", value: 96.2, benchmark: 91.8 },
        { label: "May 25", value: 98.4, benchmark: 93.5 },
      ],
      historyUnit: "Projected net tuition ($M)",
      notes: [
        "Discount rate is 52.1%, essentially flat against last cycle.",
        "The projection moves with conversion, not with new application volume.",
      ],
    },
  },
  {
    id: "yield",
    topic: "admissions",
    label: "Yield",
    icon: "◎",
    format: "percent",
    source: "modeled",
    frames: {
      yesterday: {
        numeric: 23.1,
        window: "Rate yesterday",
        delta: "0.4pp",
        direction: "down",
        favorable: false,
        comparison: "vs yesterday",
        points: [24.4, 24.1, 23.9, 23.7, 23.5, 23.4, 23.2, 23.1],
        target: "Target 26.0%",
        targetProgress: 89,
        note: "Yield moves slowly; treat single-day changes as noise.",
      },
      week: {
        numeric: 22.8,
        window: "Rate this week",
        delta: "0.9pp",
        direction: "down",
        favorable: false,
        comparison: "vs last week",
        points: [24.6, 24.2, 23.9, 23.6, 23.3, 23.1, 22.9, 22.8],
        target: "Target 26.0%",
        targetProgress: 88,
        note: "Weekly yield has declined for four consecutive weeks.",
      },
      month: {
        numeric: 23.4,
        window: "Rate this month",
        delta: "0.2pp",
        direction: "down",
        favorable: false,
        comparison: "vs last month",
        points: [24.1, 24.0, 23.8, 23.7, 23.6, 23.5, 23.4, 23.4],
        target: "Target 26.0%",
        targetProgress: 90,
        note: "Nearly flat month over month — the cycle gap is the concern.",
      },
      year: {
        numeric: 23.7,
        window: "Cycle to date",
        delta: "0.6pp",
        direction: "down",
        favorable: false,
        comparison: "vs last year",
        points: [25.1, 24.9, 24.6, 24.4, 24.2, 24.0, 23.8, 23.7],
        target: "Target 26.0%",
        targetProgress: 91,
        note: "0.6 points behind last cycle and 2.3 points below plan.",
      },
    },
    detail: {
      definition: "Enrolled students divided by admitted students, projected to census from the current deposit curve.",
      owner: "Institutional Research · Sam Oduya",
      updated: "7:30 AM ET",
      segments: [
        { label: "Residential", value: "27.4%", delta: "+0.3pp", favorable: true },
        { label: "Commuter", value: "18.2%", delta: "−2.1pp", favorable: false },
        { label: "Transfer", value: "31.6%", delta: "+1.8pp", favorable: true },
        { label: "Out-of-state", value: "16.4%", delta: "−0.9pp", favorable: false },
      ],
      history: [
        { label: "2021", value: 25.8, benchmark: 26.0 },
        { label: "2022", value: 25.2, benchmark: 26.0 },
        { label: "2023", value: 24.6, benchmark: 26.0 },
        { label: "2024", value: 24.3, benchmark: 26.0 },
        { label: "2025", value: 24.3, benchmark: 26.0 },
        { label: "2026 proj.", value: 23.7, benchmark: 26.0 },
      ],
      historyUnit: "Yield (%)",
      notes: [
        "Benchmark line is the enrollment plan target of 26.0%.",
        "A five-year drift of 2.1 points suggests a structural conversion issue, not a one-cycle dip.",
      ],
    },
  },
  {
    id: "aid-verified",
    topic: "financial_aid",
    label: "Aid Files Cleared",
    icon: "▤",
    format: "int",
    source: "modeled",
    frames: {
      yesterday: {
        numeric: 86,
        window: "Cleared yesterday",
        delta: "9.4%",
        direction: "up",
        favorable: true,
        comparison: "vs yesterday",
        points: [62, 68, 71, 74, 72, 78, 81, 86],
        target: "Pace 95/day",
        targetProgress: 91,
        note: "Best single day since two reviewers went on leave.",
      },
      week: {
        numeric: 402,
        window: "Cleared this week",
        delta: "6.2%",
        direction: "up",
        favorable: true,
        comparison: "vs last week",
        points: [318, 336, 351, 364, 372, 384, 394, 402],
        target: "Pace 460/wk",
        targetProgress: 87,
        note: "Still 58 files short of the pace needed to clear the backlog.",
      },
      month: {
        numeric: 1540,
        window: "Cleared this month",
        delta: "14.8%",
        direction: "up",
        favorable: true,
        comparison: "vs last month",
        points: [1040, 1160, 1258, 1332, 1408, 1462, 1504, 1540],
        target: "Plan 1,700",
        targetProgress: 91,
        note: "Throughput is improving; arrivals are still outpacing it.",
      },
      year: {
        numeric: 5318,
        window: "Cycle to date",
        delta: "11.2%",
        direction: "up",
        favorable: true,
        comparison: "vs last year",
        points: [1840, 2420, 3010, 3520, 4080, 4560, 4960, 5318],
        target: "Target 6,400",
        targetProgress: 83,
        note: "Ahead of last cycle, but the queue grew faster than capacity.",
      },
    },
    detail: {
      definition: "Financial aid files that completed verification and moved to packaging.",
      owner: "Financial Aid Operations · Priya Shah",
      updated: "7:30 AM ET",
      segments: [
        { label: "V1 standard", value: "3,180", delta: "+12.6%", favorable: true },
        { label: "V4 identity", value: "742", delta: "+4.1%", favorable: true },
        { label: "V5 aggregate", value: "684", delta: "−2.8%", favorable: false },
        { label: "Professional judgment", value: "712", delta: "+18.4%", favorable: true },
      ],
      history: [
        { label: "Dec", value: 420, benchmark: 380 },
        { label: "Jan", value: 1180, benchmark: 1040 },
        { label: "Feb", value: 2140, benchmark: 1920 },
        { label: "Mar", value: 3080, benchmark: 2780 },
        { label: "Apr", value: 3960, benchmark: 3610 },
        { label: "May", value: 5318, benchmark: 4782 },
      ],
      historyUnit: "Cumulative files cleared",
      notes: [
        "Benchmark line is the same point in the Fall 2025 cycle.",
        "Two temporary reviewers would raise the daily clear rate from 72 to 96.",
      ],
    },
  },
  {
    id: "persistence",
    topic: "student_success",
    label: "Deposit → Orientation",
    icon: "◇",
    format: "percent",
    source: "modeled",
    frames: {
      yesterday: {
        numeric: 91.4,
        window: "Rate yesterday",
        delta: "0.4pp",
        direction: "up",
        favorable: true,
        comparison: "vs yesterday",
        points: [89.8, 90.1, 90.4, 90.6, 90.9, 91.0, 91.2, 91.4],
        target: "Target 94.0%",
        targetProgress: 97,
        note: "Orientation registration sweep is showing early results.",
      },
      week: {
        numeric: 90.8,
        window: "Rate this week",
        delta: "0.6pp",
        direction: "down",
        favorable: false,
        comparison: "vs last week",
        points: [92.0, 91.8, 91.6, 91.4, 91.2, 91.0, 90.9, 90.8],
        target: "Target 94.0%",
        targetProgress: 96,
        note: "First-generation deposits are the segment pulling this down.",
      },
      month: {
        numeric: 91.9,
        window: "Rate this month",
        delta: "1.1pp",
        direction: "up",
        favorable: true,
        comparison: "vs last month",
        points: [90.2, 90.5, 90.9, 91.2, 91.4, 91.6, 91.8, 91.9],
        target: "Target 94.0%",
        targetProgress: 98,
        note: "Coach assignment coverage rose from 32% to 46% this month.",
      },
      year: {
        numeric: 92.3,
        window: "Cycle to date",
        delta: "0.8pp",
        direction: "up",
        favorable: true,
        comparison: "vs last year",
        points: [88.6, 89.4, 90.1, 90.8, 91.3, 91.7, 92.0, 92.3],
        target: "Target 94.0%",
        targetProgress: 98,
        note: "Ahead of last cycle, still 1.7 points short of plan.",
      },
    },
    detail: {
      definition:
        "Share of deposited students who complete orientation registration, the earliest reliable melt indicator.",
      owner: "Student Success · Marcus Bell",
      updated: "7:30 AM ET",
      segments: [
        { label: "Continuing-generation", value: "95.1%", delta: "+0.6pp", favorable: true },
        { label: "First-generation", value: "86.4%", delta: "−1.8pp", favorable: false },
        { label: "Transfer", value: "93.8%", delta: "+2.1pp", favorable: true },
        { label: "Commuter", value: "88.2%", delta: "−0.9pp", favorable: false },
      ],
      history: [
        { label: "2022", value: 90.1, benchmark: 94.0 },
        { label: "2023", value: 90.8, benchmark: 94.0 },
        { label: "2024", value: 91.2, benchmark: 94.0 },
        { label: "2025", value: 91.5, benchmark: 94.0 },
        { label: "2026 proj.", value: 92.3, benchmark: 94.0 },
      ],
      historyUnit: "Deposit-to-orientation (%)",
      notes: [
        "Students with a named coach before June 15 melted at 4.1% last cycle versus 11.8% without.",
        "142 deposited students have not yet registered for orientation.",
      ],
    },
  },
  {
    id: "housing-contracts",
    topic: "housing",
    label: "Housing Contracts",
    icon: "⌂",
    format: "int",
    source: "modeled",
    frames: {
      yesterday: { numeric: 48, window: "Signed yesterday", delta: "5.2%", direction: "up", favorable: true, comparison: "vs yesterday", points: [31, 36, 39, 37, 42, 44, 46, 48], target: "Pace 54/day", targetProgress: 89, note: "Room selection opening lifted same-day signings." },
      week: { numeric: 274, window: "Signed this week", delta: "7.8%", direction: "up", favorable: true, comparison: "vs last week", points: [206, 221, 234, 242, 251, 260, 268, 274], target: "Pace 310/wk", targetProgress: 88, note: "23 deposit-paid students still cannot enter selection." },
      month: { numeric: 902, window: "Signed this month", delta: "11.4%", direction: "up", favorable: true, comparison: "vs last month", points: [612, 668, 714, 762, 806, 848, 878, 902], target: "Plan 1,010", targetProgress: 89, note: "Ahead of the residential occupancy plan." },
      year: { numeric: 1190, window: "Cycle to date", delta: "4.6%", direction: "up", favorable: true, comparison: "vs last year", points: [284, 428, 596, 742, 884, 1004, 1108, 1190], target: "Target 1,450", targetProgress: 82, note: "Contracts are tracking ahead of deposits — a healthy sign." },
    },
    detail: {
      definition: "Signed housing contracts for Fall 2026, net of cancellations.",
      owner: "Housing & Residence Life · Elena Ruiz",
      updated: "7:30 AM ET",
      segments: [
        { label: "Residence halls", value: "812", delta: "+6.1%", favorable: true },
        { label: "Apartments", value: "244", delta: "+2.8%", favorable: true },
        { label: "Student village", value: "134", delta: "−1.4%", favorable: false },
        { label: "Blocked from selection", value: "23", delta: "+9 today", favorable: false },
      ],
      history: [
        { label: "Feb", value: 284, benchmark: 302 },
        { label: "Mar", value: 596, benchmark: 604 },
        { label: "Apr", value: 884, benchmark: 862 },
        { label: "May 11", value: 1004, benchmark: 968 },
        { label: "May 18", value: 1108, benchmark: 1054 },
        { label: "May 25", value: 1190, benchmark: 1138 },
      ],
      historyUnit: "Cumulative contracts",
      notes: [
        "Contracts running ahead of deposits usually signals genuine intent.",
        "The 23 blocked students are an operational fix, not an outreach problem.",
      ],
    },
  },
  {
    id: "registration-holds",
    topic: "registrar",
    label: "Registration Holds",
    icon: "⊘",
    format: "int",
    source: "modeled",
    frames: {
      yesterday: { numeric: 41, window: "Cleared yesterday", delta: "18.2%", direction: "up", favorable: true, comparison: "vs yesterday", points: [18, 22, 26, 24, 31, 34, 36, 41], target: "Pace 45/day", targetProgress: 91, note: "Batch release cleared the largest group this month." },
      week: { numeric: 186, window: "Cleared this week", delta: "9.4%", direction: "up", favorable: true, comparison: "vs last week", points: [128, 142, 154, 161, 168, 174, 180, 186], target: "Pace 210/wk", targetProgress: 89, note: "Transcript evaluation remains the slowest queue." },
      month: { numeric: 648, window: "Cleared this month", delta: "6.8%", direction: "up", favorable: true, comparison: "vs last month", points: [412, 468, 512, 552, 586, 612, 632, 648], target: "Plan 720", targetProgress: 90, note: "Steady throughput, but arrivals are flat." },
      year: { numeric: 2418, window: "Open holds remaining", delta: "3.1%", direction: "down", favorable: true, comparison: "vs last year", points: [3180, 3020, 2884, 2742, 2640, 2544, 2472, 2418], target: "Target 2,000", targetProgress: 83, note: "204 transfer admits are waiting on a credit decision." },
    },
    detail: {
      definition: "Registration holds preventing course enrollment for admitted and continuing students.",
      owner: "Registrar · Sam Oduya",
      updated: "7:30 AM ET",
      segments: [
        { label: "Transcript evaluation", value: "946", delta: "−4.2%", favorable: true },
        { label: "Financial", value: "812", delta: "+2.1%", favorable: false },
        { label: "Immunization", value: "418", delta: "−8.6%", favorable: true },
        { label: "Advising", value: "242", delta: "−1.1%", favorable: true },
      ],
      history: [
        { label: "Jan", value: 3180, benchmark: 3240 },
        { label: "Feb", value: 3020, benchmark: 3110 },
        { label: "Mar", value: 2742, benchmark: 2880 },
        { label: "Apr", value: 2544, benchmark: 2660 },
        { label: "May", value: 2418, benchmark: 2494 },
      ],
      historyUnit: "Open registration holds",
      notes: [
        "Lower is better — the benchmark line is the same point last cycle.",
        "Batch evaluation of the top three feeder schools would clear 61% of the transcript queue.",
      ],
    },
  },
];

/* ------------------------------------------------------------ since yesterday */

export const BREW_CHANGES: BrewChange[] = [
  {
    id: "verification-overnight",
    topic: "financial_aid",
    time: "6:10 AM",
    title: "Verification topic cleared 86 files overnight",
    detail: "Best single day since two reviewers went on leave. 468 cases remain open.",
    tone: "positive",
    source: "modeled",
    destination: "tasks",
    metric: "+86 files",
  },
  {
    id: "commuter-deposits",
    topic: "admissions",
    time: "7:02 AM",
    title: "Commuter deposits fell below the seven-day average",
    detail: "64 deposits posted yesterday against a 74/day pace. Commuter accounts for the whole gap.",
    tone: "watch",
    source: "modeled",
    destination: "outreach",
    metric: "−10 vs pace",
  },
  {
    id: "early-alerts",
    topic: "student_success",
    time: "5:45 AM",
    title: "14 new early-alert flags on deposited students",
    detail: "Nine are first-generation students with no orientation registration.",
    tone: "watch",
    source: "workspace",
    destination: "students",
    metric: "14 new flags",
  },
  {
    id: "appeals",
    topic: "financial_aid",
    time: "Yesterday · 4:40 PM",
    title: "Appeal committee approved 22 of 27 packages",
    detail: "Median award increase was $2,840. Five cases returned for documentation.",
    tone: "positive",
    source: "modeled",
    destination: "tasks",
    metric: "81% approved",
  },
  {
    id: "transfer-milestone",
    topic: "admissions",
    time: "Yesterday · 3:15 PM",
    title: "Transfer applications crossed 1,400 for the cycle",
    detail: "Business and Health Sciences account for two thirds of the year-over-year lift.",
    tone: "positive",
    source: "modeled",
    destination: "students",
    metric: "1,412 total",
  },
  {
    id: "room-selection",
    topic: "housing",
    time: "Yesterday · 9:00 AM",
    title: "Room selection opened to 1,190 deposited students",
    detail: "23 students are blocked by a prerequisite the housing portal cannot yet see.",
    tone: "watch",
    source: "modeled",
    destination: "campus_life",
    metric: "23 blocked",
  },
  {
    id: "holds-cleared",
    topic: "registrar",
    time: "Yesterday · 2:20 PM",
    title: "Spring transcript holds dropped by 41",
    detail: "Batch release cleared the largest group of registration blockers this month.",
    tone: "positive",
    source: "modeled",
    destination: "academics",
    metric: "−41 holds",
  },
];

/* ----------------------------------------------------------------- calendar */

export const BREW_MEETINGS: BrewMeeting[] = [
  {
    id: "leadership-huddle",
    time: "8:30 AM",
    duration: "45 min",
    title: "Enrollment Leadership Huddle",
    detail: "Review key metrics and insights",
    priority: "high",
    attendees: ["DW", "MB", "SO"],
    extraAttendees: "+5",
    location: "Whitmore Hall 214 · Teams link",
    organizer: "Dana Whitfield, AVP Enrollment",
    agenda: [
      "Deposit pace against the Fall 2026 plan",
      "Commuter conversion gap and the aid-completion backlog",
      "Transfer momentum and feeder-school event capacity",
      "Decisions needed before the June 1 deposit deadline",
    ],
    prep: [
      "Bring the verification staffing recommendation — you own that decision.",
      "Deposit rate is 1.7 points behind last cycle; commuter explains 78% of it.",
      "Transfer volume is the good news to lead with.",
    ],
    destination: "overview",
  },
  {
    id: "campaign-review",
    time: "10:00 AM",
    duration: "30 min",
    title: "Campaign Review – Commuter Outreach",
    detail: "Marketing, Comms",
    priority: "medium",
    attendees: ["KS", "RB"],
    location: "Teams",
    organizer: "Kara Simmons, Enrollment Marketing",
    agenda: [
      "Performance of the May commuter email sequence",
      "Two-step nudge concept: missing document, then deadline",
      "Paid social spend reallocation toward GA and NC markets",
    ],
    prep: [
      "312 commuter admits are aid-incomplete — that is the audience to name.",
      "Ask for the message to reference the specific missing document, not a generic reminder.",
    ],
    destination: "outreach",
  },
  {
    id: "verification-standup",
    time: "11:30 AM",
    duration: "25 min",
    title: "Verification Staffing Check-in",
    detail: "Financial Aid Operations",
    priority: "medium",
    attendees: ["JT", "SA"],
    location: "Financial Aid conference room",
    organizer: "Jamie Torres, Verification Lead",
    agenda: [
      "Daily clear rate against the 95/day service target",
      "Temporary reviewer onboarding timeline",
      "Queue re-sequencing by deposit probability",
    ],
    prep: ["Confirm whether the two temporary reviewers are approved before this meeting."],
    destination: "tasks",
  },
  {
    id: "aid-ops-sync",
    time: "1:00 PM",
    duration: "45 min",
    title: "Financial Aid Operations Sync",
    detail: "FA, Ops, Enrollment",
    priority: "high",
    attendees: ["JT", "SA", "DW"],
    location: "Whitmore Hall 118",
    organizer: "You",
    agenda: [
      "Decision: approve two temporary verification reviewers",
      "Appeal committee cadence through the deposit deadline",
      "Packaging turnaround for the commuter segment",
      "Vendor SLA change and what it means for June",
    ],
    prep: [
      "This is where the staffing decision lands. Backlog clears May 29 with the addition, June 14 without.",
      "Appeal median is 7.8 days against a 5-day published standard.",
    ],
    destination: "tasks",
  },
  {
    id: "provost-1on1",
    time: "3:30 PM",
    duration: "30 min",
    title: "1:1 with Provost",
    detail: "Weekly update",
    priority: "low",
    attendees: ["EP"],
    location: "Provost's office",
    organizer: "Provost Elena Park",
    agenda: [
      "Scholarship reallocation request awaiting your approval",
      "Net tuition projection and the gap to the $110M target",
      "Board enrollment update draft",
    ],
    prep: [
      "The provost's reallocation email from 6:45 AM asks for a decision before noon.",
      "Net tuition projection is $98.4M, up 5.2% year over year but $11.6M below plan.",
    ],
    destination: "messages",
  },
];

/**
 * A stable portrait per colleague, so the same attendee looks the same in the
 * agenda and in the meeting detail. Falls back to a hash for unknown initials.
 */
const ATTENDEE_ROSTER = [...new Set(BREW_MEETINGS.flatMap((meeting) => meeting.attendees))];
const AVATAR_COUNT = 8;

export function attendeeAvatar(initials: string): string {
  const known = ATTENDEE_ROSTER.indexOf(initials);
  if (known >= 0) return `/media/avatars/attendee-${(known % AVATAR_COUNT) + 1}.svg`;
  let hash = 0;
  for (let index = 0; index < initials.length; index += 1) {
    hash = (hash * 31 + initials.charCodeAt(index)) % 997;
  }
  return `/media/avatars/attendee-${(hash % AVATAR_COUNT) + 1}.svg`;
}

/* -------------------------------------------------------------------- email */

export const BREW_EMAILS: BrewEmail[] = [
  {
    id: "provost-reallocation",
    time: "6:45 AM",
    sender: "Office of the Provost",
    senderRole: "Elena Park, Provost",
    subject: "Provost: Reallocation Request – Scholarship Initiative",
    summary: "Request to approve additional scholarship funds for commuter outreach.",
    priority: "high",
    topic: "financial_aid",
    body: [
      "Priya — following our conversation on Friday, I would like to move $340,000 from the unallocated merit pool into a targeted commuter scholarship for the remainder of this cycle.",
      "The rationale is the conversion gap you flagged. If commuter deposits are lagging because of affordability rather than interest, a modest, well-targeted award should move the number more efficiently than another round of outreach.",
      "I need your read before noon so we can put it in front of the budget committee this week. Specifically: is affordability the binding constraint here, or is it the verification wait?",
    ],
    asks: [
      "Approve or redirect the $340K reallocation",
      "Confirm whether affordability or process delay is the binding constraint",
      "Respond before noon for the budget committee",
    ],
    thread: [
      {
        sender: "Elena Park",
        time: "Friday · 4:10 PM",
        excerpt: "Can you pull the commuter deposit numbers before we talk to the budget committee?",
      },
      {
        sender: "You",
        time: "Friday · 5:32 PM",
        excerpt: "Sending the segment breakdown. The gap is concentrated in aid-incomplete files.",
      },
    ],
    suggestedReply: {
      subject: "Re: Reallocation Request – Scholarship Initiative",
      greeting: "Elena,",
      body: [
        "Thanks for moving quickly on this. My read is that process delay — not affordability — is the binding constraint right now.",
        "312 commuter admits are sitting behind an incomplete aid file, and median verification wait has gone from 6.1 to 11.2 days. Students in that group convert at 61% when their file clears inside seven days and 24% after that. A larger award does not help a family that has not yet seen a final package.",
        "My recommendation: hold the $340K for now and approve two temporary verification reviewers instead — roughly $9,400 for three weeks. That pulls the backlog clear date from June 14 to May 29, ahead of the deposit deadline. If the gap persists after the queue clears, affordability becomes the credible explanation and I would support the reallocation then.",
        "I can have the staffing decision confirmed by 1:00 PM today and will bring the updated deposit curve to the budget committee.",
      ],
      signoff: "Priya",
    },
    destination: "messages",
  },
  {
    id: "board-update",
    time: "5:15 AM",
    sender: "Board Relations",
    senderRole: "Marcus Bell, Dean of Students",
    subject: "Board of Trustees: Upcoming Enrollment Update",
    summary: "Reminder: Enrollment update requested for June board meeting.",
    priority: "high",
    topic: "admissions",
    body: [
      "The June board packet closes Friday. The enrollment section needs a yield-risk paragraph and an updated net tuition outlook.",
      "Trustees asked specifically about the commuter segment after the April meeting, so please address it directly rather than in aggregate.",
      "Two pages maximum. I can draft the narrative if you send me the numbers and the framing you want.",
    ],
    asks: [
      "Provide the yield-risk paragraph",
      "Confirm the net tuition outlook figure",
      "Address the commuter segment explicitly",
    ],
    thread: [
      {
        sender: "Marcus Bell",
        time: "May 12 · 9:04 AM",
        excerpt: "April packet landed well. Trustees want more on commuter conversion next time.",
      },
    ],
    suggestedReply: {
      subject: "Re: Board of Trustees: Upcoming Enrollment Update",
      greeting: "Marcus,",
      body: [
        "Here is the framing I would use, and I am happy for you to draft from it.",
        "Net tuition is projected at $98.4M, up 5.2% year over year and $11.6M below the planning target. Applications and admits are both ahead of last cycle. The gap is entirely conversion: deposit rate is 40.1% against a 45.0% target, and yield is 23.7% against 26.0%.",
        "On commuter specifically — that segment converts at 33.2%, down 6.4 points year over year, while every other segment is flat or improving. Our analysis points to process delay rather than price: verification wait time doubled to 11.2 days, and 312 commuter admits are waiting on an incomplete aid file. We are adding verification capacity this week to clear that before the deposit deadline.",
        "I will send final numbers Thursday morning so you have a day before the packet closes.",
      ],
      signoff: "Priya",
    },
    destination: "messages",
  },
  {
    id: "high-school-visit",
    time: "Yesterday",
    sender: "Regional Recruitment",
    senderRole: "Kara Simmons, Enrollment Marketing",
    subject: "Regional High School Visit This Week",
    summary: "Schedule and talking points are ready for your visit to Northview High School.",
    priority: "medium",
    topic: "admissions",
    body: [
      "Your Northview visit is Thursday at 10:00 AM. Counselor breakfast first, then two junior sessions and a financial aid Q&A for families at 6:00 PM.",
      "Northview sent 218 applications this cycle, up 31%. Their counseling topic has been asking for a plain-language aid timeline they can hand to families.",
      "Talking points and the one-page aid timeline are attached. Let me know if you want changes before we print.",
    ],
    asks: ["Review the talking points", "Approve the family aid timeline handout"],
    thread: [],
    suggestedReply: {
      subject: "Re: Regional High School Visit This Week",
      greeting: "Kara,",
      body: [
        "Thursday works. The talking points look right — one addition for the family Q&A.",
        "Please add a line on what happens after a file is selected for verification, including the documents families should have ready. That is where most of our timeline slips, and setting the expectation up front saves everyone a phone call in July.",
        "The aid timeline handout is approved. Print enough for both junior sessions as well as the evening Q&A.",
      ],
      signoff: "Priya",
    },
    destination: "outreach",
  },
  {
    id: "vendor-sla",
    time: "6:10 AM",
    sender: "Verification Services",
    senderRole: "Account topic, Meridian Verify",
    subject: "Service level change effective June 1",
    summary: "Vendor turnaround moves from 48 to 72 hours during peak season.",
    priority: "medium",
    topic: "financial_aid",
    body: [
      "Effective June 1, standard document review turnaround moves from 48 to 72 hours through the peak season.",
      "Expedited review remains at 24 hours and is available for up to 15% of monthly volume at no additional cost.",
    ],
    asks: ["Decide whether to reserve expedited capacity for commuter and transfer files"],
    thread: [],
    suggestedReply: {
      subject: "Re: Service level change effective June 1",
      greeting: "Hello,",
      body: [
        "Understood on the standard turnaround change. We would like to reserve our full expedited allocation for the June cycle.",
        "Please apply expedited review to files we tag as deposit-critical — primarily commuter and transfer admits with deadlines inside seven days. Our operations lead, Jamie Torres, will send the tagging convention today.",
        "Please confirm the allocation in writing so we can plan the June queue around it.",
      ],
      signoff: "Priya",
    },
    destination: "tasks",
  },
  {
    id: "appeal-agenda",
    time: "Yesterday",
    sender: "Appeals Coordinator",
    senderRole: "Sara Ahmed, Financial Aid",
    subject: "Thursday appeal committee agenda",
    summary: "27 appeals queued, 41 currently past the five-day service standard.",
    priority: "low",
    topic: "financial_aid",
    body: [
      "Agenda for Thursday is attached. 27 appeals are queued and 41 are past our published five-day standard.",
      "If you want to add a Tuesday session through June 5, I can hold the room and poll the committee today.",
    ],
    asks: ["Approve a second weekly committee session through June 5"],
    thread: [],
    suggestedReply: {
      subject: "Re: Thursday appeal committee agenda",
      greeting: "Sara,",
      body: [
        "Yes — please hold a Tuesday session through June 5 and poll the committee today.",
        "Two sessions a week clears the standing queue in about eleven days and brings our median decision time back under five days before the deposit deadline.",
        "Also, please pre-screen appeals with complete documentation. Roughly a third are straightforward approvals that do not need full committee discussion.",
      ],
      signoff: "Priya",
    },
    destination: "tasks",
  },
];

/* --------------------------------------------------------------- priorities */

export const BREW_PRIORITIES: BrewPriority[] = [
  {
    id: "verification-surge",
    topic: "financial_aid",
    title: "Financial Aid Verification Surge",
    level: "High",
    detail: "324 students need documents to complete files. Take action to protect yield.",
    icon: "⚑",
    linkLabel: "View students",
    destination: "students",
    source: "workspace",
    window: "Today",
    breakdown: [
      { label: "Files awaiting documents", value: "324" },
      { label: "Deadlines inside 7 days", value: "12" },
      { label: "Commuter admits affected", value: "312" },
      { label: "Median wait", value: "11.2 days" },
    ],
    steps: [
      "Approve two temporary reviewers to restore 96 files/day throughput.",
      "Re-sequence the queue by deposit probability rather than submission date.",
      "Auto-request the three documents that cover 78% of holds.",
    ],
  },
  {
    id: "campus-visits",
    topic: "admissions",
    title: "Events & Campus Visits",
    level: "Medium",
    detail: "Weekend event attendance is down 12% vs last year. Review outreach plan.",
    icon: "▦",
    linkLabel: "View details",
    destination: "campus_life",
    source: "modeled",
    window: "This week",
    breakdown: [
      { label: "Weekend registrations", value: "418" },
      { label: "Year-over-year change", value: "−12%" },
      { label: "Show rate", value: "71%" },
      { label: "Deposit lift from visits", value: "+18pp" },
    ],
    steps: [
      "Add two evening sessions for transfer and commuter families.",
      "Move confirmation reminders from 48 hours to 24 hours before the event.",
      "Pair each visit with a same-day aid appointment offer.",
    ],
  },
  {
    id: "scholarship-roi",
    topic: "financial_aid",
    title: "Scholarship ROI Review",
    level: "Low",
    detail: "Early results show high ROI in GA and NC markets. Consider reallocating spend.",
    icon: "◈",
    linkLabel: "View details",
    destination: "knowledge",
    source: "modeled",
    window: "This month",
    breakdown: [
      { label: "GA market yield", value: "31.4%" },
      { label: "NC market yield", value: "29.8%" },
      { label: "Cost per enrolled student", value: "$4,120" },
      { label: "Portfolio average", value: "$6,480" },
    ],
    steps: [
      "Model a $340K shift toward GA and NC before the provost's noon deadline.",
      "Hold the reallocation until the verification backlog clears so the signal stays clean.",
    ],
  },
  {
    id: "commuter-outreach",
    topic: "admissions",
    title: "Commuter Deposit Outreach",
    level: "High",
    detail: "312 high-probability admits are one document away from depositing.",
    icon: "✦",
    linkLabel: "View outreach",
    destination: "outreach",
    source: "modeled",
    window: "Today",
    breakdown: [
      { label: "Target audience", value: "312" },
      { label: "Modeled conversion if cleared in 7 days", value: "61%" },
      { label: "Modeled conversion after 7 days", value: "24%" },
      { label: "Net tuition at stake", value: "$1.8M" },
    ],
    steps: [
      "Send the two-step nudge naming the exact missing document.",
      "Open two same-day afternoon aid appointment blocks.",
    ],
  },
  {
    id: "melt-coaches",
    topic: "student_success",
    title: "First-Generation Coach Coverage",
    level: "Medium",
    detail: "46% of first-generation deposits still have no named success coach.",
    icon: "◇",
    linkLabel: "View students",
    destination: "students",
    source: "modeled",
    window: "This week",
    breakdown: [
      { label: "First-generation deposits", value: "758" },
      { label: "With a named coach", value: "349" },
      { label: "Flagged with 2+ melt signals", value: "68" },
      { label: "Melt rate without a coach", value: "11.8%" },
    ],
    steps: [
      "Assign coaches to all first-generation deposits before June 15.",
      "Run an orientation registration sweep on the 142 unregistered deposits.",
    ],
  },
];

/* --------------------------------------------------------------------- news */

export const BREW_NEWS: BrewNewsItem[] = [
  {
    id: "enrollment-trends",
    sourceName: "Inside Higher Ed",
    published: "This morning",
    headline: "Enrollment Trends: What Institutions Need to Know for Fall 2026",
    readTime: "2 min read",
    image: "/media/news/enrollment-trends.svg",
    imageAlt: "Illustration of a desk with an open notebook and enrollment charts",
    topics: ["admissions", "student_success"],
    category: "Industry",
    summary:
      "National application volume is up for a third consecutive year while conversion continues to slip, widening the gap between interest and enrollment.",
    keyPoints: [
      "Applications per student rose again; institutions are competing inside larger consideration sets.",
      "Median deposit rates fell 1.4 points nationally, concentrated in commuter and regional segments.",
      "Institutions that shortened aid-package turnaround reported the smallest conversion declines.",
    ],
    relevance:
      "This is the national version of your commuter gap. Your applications are up 5.6% while deposit rate is down 1.7 points — the same pattern, and the reported remedy is exactly the verification throughput work already on your desk.",
  },
  {
    id: "yield-strategies",
    sourceName: "EAB",
    published: "Yesterday",
    headline: "5 Proven Strategies to Improve Yield in a Competitive Market",
    readTime: "3 min read",
    image: "/media/news/yield-strategies.svg",
    imageAlt: "Illustration of a phone showing a rising yield chart",
    topics: ["admissions", "financial_aid"],
    category: "Research",
    summary:
      "A synthesis of yield interventions across 140 institutions, ranked by measured lift against cost.",
    keyPoints: [
      "Naming the specific missing document in outreach outperformed generic reminders by 3.2x.",
      "Same-day aid appointments produced the largest single lift for commuter families.",
      "Awards increased after a student has stalled rarely recover the deposit.",
    ],
    relevance:
      "Two of the five highest-lift plays are already in your recommended actions today. The third finding argues against the provost's reallocation request until the queue clears.",
  },
  {
    id: "fafsa-pressure",
    sourceName: "The Chronicle",
    published: "Yesterday",
    headline: "Financial Aid Pressure Continues as FAFSA Completion Lags",
    readTime: "2 min read",
    image: "/media/news/fafsa-pressure.svg",
    imageAlt: "Illustration of a campus administration building",
    topics: ["financial_aid"],
    category: "Industry",
    summary:
      "Verification selection rates remain elevated, and aid offices report median turnaround times well past published service standards.",
    keyPoints: [
      "Selection rates are running above pre-2024 norms at most public institutions.",
      "Temporary reviewer capacity was the most common short-term response.",
      "Offices that re-sequenced queues by enrollment probability protected more revenue than those working first-in-first-out.",
    ],
    relevance:
      "Your 11.2-day median and 468-case queue put you in the middle of this pattern. Both remedies described here are the ones on your 1:00 PM agenda.",
  },
  {
    id: "ai-enrollment",
    sourceName: "Higher Ed Dive",
    published: "2 days ago",
    headline: "AI in Enrollment: Moving from Pilot to Performance",
    readTime: "3 min read",
    image: "/media/news/ai-enrollment.svg",
    imageAlt: "Illustration of a lecture hall with data overlays",
    topics: ["admissions", "student_success", "financial_aid"],
    category: "Technology",
    summary:
      "Institutions are moving predictive enrollment models out of pilot and into daily operations, with mixed governance maturity.",
    keyPoints: [
      "The strongest results came from models embedded in daily staff workflow rather than quarterly reports.",
      "Governance gaps concentrate around explainability of student-level scores.",
      "Human review of recommended actions remained standard practice at every institution surveyed.",
    ],
    relevance:
      "Your recommended actions already run inside the daily workflow. The governance section is worth forwarding to Institutional Research before the June board packet closes.",
  },
  {
    id: "verification-guidance",
    sourceName: "Federal Register",
    published: "3 days ago",
    headline: "New Verification Guidance Narrows Selection Criteria",
    readTime: "4 min read",
    image: "/media/news/verification-guidance.svg",
    imageAlt: "Illustration of policy documents and a seal",
    topics: ["financial_aid", "registrar"],
    category: "Policy",
    summary:
      "Draft guidance would narrow verification selection criteria beginning with the following award year.",
    keyPoints: [
      "Selection would shift toward targeted risk indicators rather than broad categories.",
      "Institutions would retain discretion to verify beyond the federal minimum.",
      "Comment period closes in 45 days.",
    ],
    relevance:
      "No action this cycle. If adopted, your queue volume would fall meaningfully next year — worth modeling before you commit to permanent staffing.",
  },
  {
    id: "direct-admission",
    sourceName: "NASFAA",
    published: "3 days ago",
    headline: "State Aid Programs Expand Direct Admission Pilots",
    readTime: "2 min read",
    image: "/media/news/direct-admission.svg",
    imageAlt: "Illustration of a pathway connecting two campuses",
    topics: ["admissions", "registrar"],
    category: "Policy",
    summary:
      "Several state systems are pairing direct admission with guaranteed aid estimates delivered at the point of admission.",
    keyPoints: [
      "Early results show faster deposit decisions when an aid estimate accompanies the offer.",
      "Transfer pathways are the fastest-growing segment in these pilots.",
      "Participating institutions report heavier front-loaded verification volume.",
    ],
    relevance:
      "Pre-packaging aid for transfer admits is already in your recommended actions. This is external evidence for the same play, and a caution about where the workload lands.",
  },
];

/* -------------------------------------------------------------- quick links */

export const BREW_QUICK_LINKS: BrewQuickLink[] = [
  { id: "dashboard", label: "Enrollment Dashboard", destination: "overview" },
  { id: "topic", label: "Team Updates", destination: "messages" },
  { id: "reports", label: "Reports Center", destination: "knowledge" },
  { id: "edward", label: "Ask Edward", destination: "edward" },
];
